### ISSUE TITLE
Overviewer for Minecraft: Bedrock Edition World Format

### ISSUE THREAD

**Issue by mtoensing** [overviewer/Minecraft-Overviewer#1662] opened 2019-10-21 09:55 UTC
I guess somebody has to ask this question: Can we somehow use the new world format with the rest of the overviewer code? At least it is documented: https://minecraft.gamepedia.com/Bedrock_Edition_level_format

**Comment by barrett777** [comment] 2019-11-21 23:35
Fyi this is a duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/921

There's a bit of discussion over there

**Closed** 2019-11-23 14:33 UTC
