### ISSUE TITLE
Feature request: Add coloured, semi-transparent, regions

### ISSUE THREAD

**Issue by forquare** [overviewer/Minecraft-Overviewer#1192] opened 2014-12-19 19:56 UTC
On my server we allow players to claim areas of land.  We record the coordinates of the four corners of their claimed land.  It was be awesome if the regions could be "highlighted" within Overviewer and toggled in the UI like POIs are.
The server is vanilla Minecraft.

**Comment by agrif** [comment] 2015-02-01 17:50
Closing as a duplicate of #642.

**Closed by agrif** 2015-02-01 17:50 UTC
