### ISSUE TITLE
Minecraft Overviewer version 0.17.39 (2402e41) crashing on Minecraft 1.18

### ISSUE THREAD

**Issue by Mickoloh** [overviewer/Minecraft-Overviewer#1996] opened 2021-12-01 03:47 UTC
```
$ /opt/minecraft/build/Minecraft-Overviewer/overviewer.py --config=/opt/minecraft/build/config.py
2021-11-30 21:11:47  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2021-11-30 21:11:47  Generating textures...
2021-11-30 21:12:16 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/opt/minecraft/build/Minecraft-Overviewer/overviewer.py", line 653, in <module>
    ret = main()
  File "/opt/minecraft/build/Minecraft-Overviewer/overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/opt/minecraft/build/Minecraft-Overviewer-0.17.39/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/opt/minecraft/build/Minecraft-Overviewer-0.17.39/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'
```

Fedora 35, Minecraft 1.18

**Comment by Unix-User** [comment] 2021-12-01 04:45
same error
```
2021-12-01 01:41:16  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2021-12-01 01:41:16  Generating textures...
2021-12-01 01:41:45 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "./overviewer.py", line 653, in <module>
    ret = main()
  File "./overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/opt/minecraft/Minecraft-Overviewer/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/opt/minecraft/Minecraft-Overviewer/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'

```

Ubuntu 20.04, Minecraft 1.18

**Comment by shnizmuffin** [comment] 2021-12-01 05:36
Same.

Debian 11, Minecraft 1.18

**Comment by ST-Electro** [comment] 2021-12-01 08:39
Same.

Ubuntu 18.04, Minecraft 1.18

**Comment by F-Node-Karlsruhe** [comment] 2021-12-01 09:04
Same here. Seems to be a general problem :)

**Comment by IncredibleHolg** [comment] 2021-12-01 11:31
This is a duplicate of #1990 

The solving pull request is within this issue,

**Comment by oscar230** [comment] 2021-12-01 20:58
### Same error here for **Minecraft 1.18** on `Debian 5.10.70-1`  and `Python 3.9.2`.

Below is the complete log.
`2021-12-01 21:53:57  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2021-12-01 21:53:57  Generating textures...
2021-12-01 21:54:12 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/opt/minecraft-overviewer/Minecraft-Overviewer/overviewer.py", line 653, in <module>
    ret = main()
  File "/opt/minecraft-overviewer/Minecraft-Overviewer/overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/opt/minecraft-overviewer/Minecraft-Overviewer/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/opt/minecraft-overviewer/Minecraft-Overviewer/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'`

**Comment by Mickoloh** [comment] 2021-12-02 02:18
> This is a duplicate of #1990
> 
> The solving pull request is within this issue,

I applied the patched code and I could successfully generate the graphics with no issues. Thank you!

**Comment by BenKennish** [comment] 2021-12-02 02:22
Same problem here.  Does someone need to approve the PR?

**Closed** 2021-12-02 18:10 UTC
