### ISSUE TITLE
Segmentation Fault (Core Dumped) Ubuntu 18.04 Bionic Beaver:

### ISSUE THREAD

**Issue by SaintFenix** [overviewer/Minecraft-Overviewer#1449] opened 2018-05-11 02:59 UTC
Hello, I've been using overviewer for years and love this piece of software, so before I go asking for help, I just wanna thank everyone involved for it. Ever player on the server, me included love you guys for this map maker.

So first off I've got a fairly exotic setup for rendering maps off my primary server.

I have the input minecraft world mounted via NFS, and the output area mounted the same way on the server where the game actually runs. I'm running overviewer on a secondary machine that can crunch away making the map without burdening the game server. Everything here is taking place on the Overviewer Crunch machine.

```
I followed the instructions from the docs to install via the deb repository, and when installing it I was hit with this error:
 19:22 user@WestGermany ~/Downloads% sudo apt install minecraft-overviewer
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 minecraft-overviewer : Depends: python-imaging but it is not installable
E: Unable to correct problems, you have held broken packages. 
```

An apt install python-imaging returns: 

```
`Package python-imaging is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  python-pil:i386 python-pil

E: Package 'python-imaging' has no installation candidate`

so I follow that up with a: `sudo apt install python-pil
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-pil is already the newest version (5.1.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.`
```

however overviewer still isn't having it, so, naturally I go out on the net and find me the piece I need: https://launchpad.net/ubuntu/bionic/amd64/python-imaging/4.1.1-3build2
it says deprecated, but seems to be alright, and it installs fine, here is the installation information for that:

```
`Python Imaging Library compatibility layer
 PIL used to provide a PIL.pth file which allowed you to `import Image` but
 this is deprecated.  Use `from PIL import Image` now, or install this
 compatibility package to temporarily get the old behavior back.
 .
 This compatibility package is built for Python 2 only.
Do you want to install the software package? [y/N]:y`
```

afterward I run overviewer.py with a configuration file with a bash script, where it greets me with a seg fault, and tells me the core is dumped:

```
./overviewer.sh: line 3:  4699 Segmentation fault      (core dumped) overviewer.py --config=/home/fenix/overviewerconfig --processes 30
```

seeing this issue: #1435 
I follow what Counterpillow suggested and run it in: gbd python 2.

here is that output:
```
Starting program: /usr/bin/python2 /usr/bin/overviewer.py --config=/home/fenix/overviewerconfig --processes 30
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2018-05-10 19:41:37  Welcome to Minecraft Overviewer!
2018-05-10 19:41:37  Generating textures...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff654a900 in alpha_over_full () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
```
any help sent my way would be muchly appreciated, I'm game to try anything. :)

**Comment by CounterPillow** [comment] 2018-05-11 06:18
This looks like the issue is that the PIL package name changed in the latest Ubuntu, and our builds need adjusting accordingly.

Thanks for reporting!

**Comment by SaintFenix** [comment] 2018-05-17 14:37
according to #1455 there is a new build of overviewer to try, and I've since updated to it, and attempted another update.

The Seg fault remains. :(

**Comment by CounterPillow** [comment] 2018-05-17 15:16
I'll close this as a duplicate of #1455 then

**Closed by CounterPillow** 2018-05-17 15:16 UTC

**Comment by Taranchul** [comment] 2019-03-30 09:58
I can confirm this on Kubuntu 18.04 64 bit. Building from source works, however. Since Ubuntu-based distributions are very widespread, and 18.04 being a Long Term Support release, may I kindly ask you to look into rebuilding the deb packages so that they don't segfault on those distros? (And hopefully, not break on other Debian-based distros in the process.)
