### ISSUE TITLE
POI markers move with changing zoom level

### ISSUE THREAD

**Issue by Bobcat00** [overviewer/Minecraft-Overviewer#1499] opened 2018-11-15 04:33 UTC
Changing the zoom level with the mouse wheel causes the POI markers to move relative to the rendered map.  Strangely, the world spawn marker is always in the correct place regardless of zoom level, but a POI marker _with the same x,y,z coordinates as the spawn marker_ moves around.

Overviewer 0.12.278 running on Win7 64 bit.  Minecraft version 1.12.2.

EDIT: The problem appears to be that the POI markers are positioned with the top left corner at the specified coordinates, instead of positioning the little bump at the bottom at those coordinates.  (I'm guessing the solution is to handle the POI markers the same as the world spawn marker, which shows up in the correct place.)

**Comment by CounterPillow** [comment] 2018-11-18 08:05
duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/1481

**Closed by CounterPillow** 2018-11-18 08:05 UTC
