### ISSUE TITLE
Manual POI Icons positioned wrongly

### ISSUE THREAD

**Issue by GuyAglionby** [overviewer/Minecraft-Overviewer#1481] opened 2018-09-16 20:10 UTC
Icons associated with manual POIs are anchored at the specified coordinates by their top-left corner, rather than the point at the bottom (or signpost, for the sign icon). Having this anchor point makes zooming look a little odd. Instead, I suggest that the anchoring be changed to be the same as the spawn and linked location POIs, which behave as expected.

**Comment by CounterPillow** [comment] 2018-09-16 22:35
Related commit is a129274aa16e68bd68ccfb27f9e38c82a80fd9b7 where I removed a fix for this which didn't work properly. It's some dumb leaflet shortcoming where you cannot specify an anchor in relative units of the icon size.

**Comment by 14mRh4X0r** [comment] 2018-10-06 15:37
> Related commit is [a129274](https://github.com/overviewer/Minecraft-Overviewer/commit/a129274aa16e68bd68ccfb27f9e38c82a80fd9b7) where I removed a fix for this which didn't work properly.

Just tested in my browser, using `margin-left` and `margin-top` instead of `left` and `top` respectively works.

**Comment by CounterPillow** [comment] 2018-11-18 08:12
Fixed, I think. Thanks @14mRh4X0r.

**Comment by Bobcat00** [comment] 2018-11-21 12:49
This is worse.  The markers are all in entirely the wrong places.  Not even close to where they should be.  Entirely unusable.

Overviewer 0.12.280
Win7 64 bit
Craftbukkit 1.12.2 map
Chrome 70.0.3538.110 64 bit

**Comment by CounterPillow** [comment] 2018-11-21 14:18
I suggest somebody else fix it then, I'm done dealing with the stupidity of CSS.

**Comment by CounterPillow** [comment] 2019-01-23 13:08
Wait, so adding it manually works, but having the same class added by Overviewer's JS doesn't?

What?

**Comment by 14mRh4X0r** [comment] 2019-01-23 20:17
Well that took some investigation. This fixes it though.

**Comment by 14mRh4X0r** [comment] 2019-01-24 14:44
For an example how it looks like, see http://mco.re/map

**Closed** 2019-02-21 14:59 UTC
Labels: Bug, Web, genPOI

**Comment by Bobcat00** [comment] 2019-02-23 14:15
This is much better, but still not right. I'm seeing the top of the markers aligned with the coordinates, when it should be the bottom of the markers.  Also, the marker is shifted slightly to the right.  I confirmed that the coordinates are defined properly.  It's certainly usable, but I just wanted to let you know.  (Maybe you want to quit while you're ahead.)

Overviewer 0.13.2 64 bit on Windows 7, with Chrome 72.0.3626.119

![overviewer](https://user-images.githubusercontent.com/3617206/53287512-20919f00-374b-11e9-80e5-2d71f59bee0c.png)

**Comment by gobo7793** [comment] 2020-04-12 17:08
I think I have an idea for a fix, but tested only on 32x37px markers and not sure if this can fix the problem at all (and this is why I don't have any pull requests for this yet):
```
.ov-marker {
    position:absolute;
    margin-left:-10px;
    margin-top:-32px;
}
```

**Comment by jmaximusix** [comment] 2021-12-10 02:08
why is this closed, this issue still exists!!! and if @gobo7793 s solution works maybe it would be worth trying to implement it!

**Comment by gobo7793** [comment] 2021-12-10 08:12
@jmaximusix maybe you could try and test PR #1966 (I didn't done it by myself yet)
