### ISSUE TITLE
GPU rendering question

### ISSUE THREAD

**Issue by ARTSQ** [overviewer/Minecraft-Overviewer#2019] opened 2021-12-24 19:44 UTC
Hi! So I was wondering if there're any plans to add posibility to render map on GPU instead of CPU?
Having good videocard, but still rely on CPU is a bit upseting :(

Or maybe I'm missing the point and it's already there?

**Comment by TheKrowi** [comment] 2021-12-26 17:08
Duplicate of #1557 and #1919.

**Closed** 2021-12-27 00:41 UTC
