### ISSUE TITLE
showspawn False breaks overview completely

### ISSUE THREAD

**Issue by bakkerthehacker** [overviewer/Minecraft-Overviewer#1453] opened 2018-05-13 22:49 UTC
I was wondering why newer leaflet maps were completely broken and it turns out that my config uses `showspawn` to hide the spawn icon.  

Setting `showspawn` to `False` breaks leaflet, instead of hiding the spawn icon.

**Comment by Chi-Yu** [comment] 2018-05-15 06:33
I just ran into the same issue. Having it set to `False` causes a JavaScript error in the console `Invalid LatLng object` which causes no map to be shown.

**Comment by DevScyu** [comment] 2018-05-20 15:59
This is also fixed in #1456

**Comment by Chi-Yu** [comment] 2018-05-21 17:49
I can't find that in the online documentation. Where am I supposed to add that?

**Comment by DevScyu** [comment] 2018-05-21 18:00
@Chi-Yu Do you have discord where i can help you? `Scyu_#0854`

**Comment by 14mRh4X0r** [comment] 2018-10-06 14:27
Just ran into this myself, the cause seems to be a combination of [tilesets.py](/overviewer_core/tilesets.py#L592) and [util.js](/overviewer_core/data/js_src/util.js#L342)

**Closed** 2018-10-09 15:04 UTC
Labels: Bug, Web

**Comment by agrif** [comment] 2018-10-09 15:29
I've merged in @14mRh4X0r's fix. If you continue to have problems, please reopen the issue!
