### ISSUE TITLE
Lighting Bug

### ISSUE THREAD

**Issue by TechieAndroid** [overviewer/Minecraft-Overviewer#1442] opened 2018-04-12 22:01 UTC
This happens in both day and night modes, night is obviously worse looking.

I'm using overviewer-win64-0.12.204.

![Night](https://imgur.com/XUGP8ag.png)

**Comment by CounterPillow** [comment] 2018-04-13 06:14
duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/1370

**Closed by CounterPillow** 2018-04-13 06:14 UTC

**Comment by magneticflux-** [comment] 2018-04-26 18:07
#1445 fixes this issue, could that get looked at and merged soon? It's annoying to have to load my scheduled Overviewer Docker image with my branch's build rather than the official download.
