### ISSUE TITLE
v0.14.66 not picking up old tiles from mc 1.13.2 after upgrade to 1.14.4

### ISSUE THREAD

**Issue by Elvi81** [overviewer/Minecraft-Overviewer#1630] opened 2019-08-17 22:54 UTC
As the title says, there's tons of chunks missing from the final render, even a forced rerender does not help.
This is the same thing that happend to me when overviewer was upgraded for mc 1.13.2, black areas where none should be.
Here's an area where there should be stuff, seems only recently visited old areas show up.
http://digital-legacy.sytes.net/mc/map/#/-695/64/-653/-4/Blockrim%20Realms%20-%20overworld/world

**Comment by CounterPillow** [comment] 2019-08-18 13:42
Try doing a `java -jar server.jar --forceUpgrade --eraseCache`

**Comment by Elvi81** [comment] 2019-08-18 20:33
A litle more showed up around the map but a lot is still missing.

**Comment by CounterPillow** [comment] 2019-08-19 17:11
Can you upload `r.-2.-2.mca` for me please?

**Comment by Elvi81** [comment] 2019-08-19 22:49
Here you go.

**Comment by Elvi81** [comment] 2019-08-19 22:52
Here you go.

[r.-2.-2.zip](https://github.com/overviewer/Minecraft-Overviewer/files/3517986/r.-2.-2.zip)

**Comment by Gerolfing** [comment] 2019-08-26 13:46
I have the same issue after upgrading my map from 1.12 to 1.14.
I used --forcerender and still I got holes in map, despite all chunks are generated. Overviewer renders only chunks which were visited by player in game on 1.14.
![Capture](https://user-images.githubusercontent.com/23654416/63695314-0ed7a400-c821-11e9-9a51-3e483d54c6db.PNG)

**Comment by CounterPillow** [comment] 2019-08-26 17:37
Let me know if the commit I just pushed fixes things. If not, I'll reopen the issue.

**Closed** 2019-08-26 17:37 UTC

**Comment by gab0rka** [comment] 2019-08-26 19:49
I had the same issue with a (quite big) map used and converted from the beta-ages. I used the same method that the patch provides for months in local, and it works for me without any problems. Thanks for the patching.

**Comment by Elvi81** [comment] 2019-08-26 22:50
Works far beter but still have black "trails" near where no one has been since the update to 1.14.4.
http://digital-legacy.sytes.net/mc/map/#/1703/64/97/-2/Blockrim%20Realms%20-%20overworld/world

**Comment by gab0rka** [comment] 2019-08-26 23:16
@Elvi81 A forceRender will solve this.

**Comment by CounterPillow** [comment] 2019-08-27 17:35
those black spots won't get solved by a forcerender. The problem is that Minecraft didn't write any lighting data for those chunks. There's nothing Overviewer can do about that.

**Comment by Elvi81** [comment] 2019-08-27 18:25
Know any way to get past this annoyence?
I tried moving around the places with the black spots and it just moved them further away and created even more.

**Comment by CounterPillow** [comment] 2019-08-27 19:05
That's odd, I wouldn't have expected them to move.

**Comment by Gerolfing** [comment] 2019-08-28 09:16
Interesting picture
![Capture](https://user-images.githubusercontent.com/23654416/63842493-57ac6b80-c98d-11e9-863c-80df25a40014.PNG)
I started to use command /wb fill (worldborder plugin), which generates chunks to the border, but this time without skipping already existing chunks, so it's the same as if player was visiting the those chunks. It's long, but it fixes this glitches. Central area of my map is already fixed thanks to this command.

**Comment by Elvi81** [comment] 2019-08-28 11:36
Looks like i need to relight all of the generated chunks in my world, i tried Lightcleaner over night but it eventauly froze up the server with java.lang.OutOfMemoryError: Java heap space, glad i made a backup before.
I do not use a worldborder plugin at all and i have old chunks back to about version 1.2 that i don't intend to regenerate.

**Comment by Gerolfing** [comment] 2019-08-29 13:31
> I do not use a worldborder plugin at all and i have old chunks back to about version 1.2 that i don't intend to regenerate.

I used worldborder not to regenerate old chunks, but to emulate loading them by player on new version, because once chunks was loaded in new version overviewer renders it correctly.
