### ISSUE TITLE
Error on Overviewer 0.12.10

### ISSUE THREAD

**Issue by umarquez** [overviewer/Minecraft-Overviewer#1155] opened 2014-09-15 23:28 UTC
When I run Overviewr I got this error:

```
2014-09-15 18:21:55 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 587, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 533, in main
    dispatch.render_all(tilesets, config['observer'])
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 51, in render_all
    self.setup_tilesets(tilesetlist)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 316, in setup_tilesets
    self.manager.set_tilesets(tilesets)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/dispatcher.py", line 194, in set_tilesets
    data[0] = self.tilesets
  File "<string>", line 2, in __setitem__
  File "/usr/lib/python2.7/multiprocessing/managers.py", line 759, in _callmethod
    kind, result = conn.recv()
EOFError
```

---
## overviewer.py --verbose --version

Minecraft Overviewer 0.12.10 (00c2782)
built on Wed Sep  3 20:25:01 2014
Build machine: x86_64 Linux-2.6.38-8-server-x86_64-with-Ubuntu-11.04-natty
Read version information from '/usr/lib/python2.7/dist-packages/overviewer_core/overviewer_version.pyc'
Python executable: '/usr/bin/python'
2.7.6 (default, Mar 22 2014, 22:59:56)
[GCC 4.8.2]

**Comment by CounterPillow** [comment] 2017-03-24 18:18
I'm going to close this for a few reasons:

1. @chuckleb's issue seems to be completely separate from the initially reported issue. Different Python version, different tracback, different error. I attribute this either to your OS giving you a wrong tmp filename, or Python 2.6 being garbage when it comes to multiprocessing and having a race condition.

2. The original issue @umarquez reported contains no info useful enough to even attempt to reproduce this. The traceback just tells us that something went wrong in the dispatcher, possibly caused by something going wrong in one of the worker processes, but without a `-p1` log (which the initial reporter didn't supply) there's no usable information.

If @umarquez still experiences this issue and can supply me with more info, I'll re-open, but until then I'll close this to avoid further issue hijacking.

**Closed by CounterPillow** 2017-03-24 18:18 UTC
