### ISSUE TITLE
Missing Repo Metadata

### ISSUE THREAD

**Issue by g2bb** [overviewer/Minecraft-Overviewer#1741] opened 2020-03-25 04:19 UTC
I am trying to install Overviewer for my new CentOS server, and I keep getting this error:
```
Failed to download metadata for repo 'overviewer'
Error: Failed to download metadata for repo 'overviewer'
```

I ran the command in verbose mode and found this:
```
Cannot download 'http://overviewer.org/rpms/8/x86_64': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried.
Failed to download metadata for repo 'overviewer'
Error: Failed to download metadata for repo 'overviewer'
```

It seems to be that when I go to that [URL](http://overviewer.org/rpms/8/x86_64) the page is giving a 404 error, not sure what is causing this, but it is completely halting the setup on my server.

**Comment by g2bb** [comment] 2020-03-30 05:41
bump

**Comment by CounterPillow** [comment] 2020-03-30 06:03
Duplicate of #1677.

**Closed by CounterPillow** 2020-03-30 06:03 UTC
