### ISSUE TITLE
Rendering issue: chunks of the map don't seem to line up, squares of land seem raised when they shouldn't be, etc

### ISSUE THREAD

**Issue by BenKennish** [overviewer/Minecraft-Overviewer#1792] opened 2020-06-26 10:33 UTC
My CentOS 8.2 Server is running the latest version of Minecraft 1.16.1 and I'm running the latest commit of Overviewer from master (9605bd8)

I compiled from source with help from the following issue ticket: #1761 

Here's the result of my latest render: http://minecraft.bennish.net/map/

It seems that certain map 'tiles' don't fit together properly (are not aligned?) or something.  In certain places, the terrain seems lifted up too high in a square area and in other places it seems that parts have been shifted in a certain direction.  It's all rather weird!  😕 

The current render settings for "A regular render" ["render1"] are set to use "smooth_lightning" render mode but I've tried it set to "lightning" and "default" and get the same problem.

I have tried completely deleting the outputdir directory contents and running again but the problem persists.

Any help would be very greatful received.
Thanks!

**Comment by BenKennish** [comment] 2020-06-26 10:47
Oops sorry I just started a new render so please don't check the link above until it's finished.  I will post another comment when the render is done and make sure future renders use a different directory.

**Comment by CounterPillow** [comment] 2020-06-26 11:20
duplicate of #1178

**Closed by CounterPillow** 2020-06-26 11:20 UTC
