### ISSUE TITLE
[1.13] Nether Lava-NetherRack Pillars

### ISSUE THREAD

**Issue by durand1w** [overviewer/Minecraft-Overviewer#1551] opened 2019-04-15 22:31 UTC
For 1.13 on Linux, I'm using version .73 of the Overviewer.  There is a rendering issue where it is showing all the hidden lava blocks and then rendering nether rack from each one to the floor.  Example can be seen in the world map below.  This was not an issue on for 1.12.

[Nether Map](http://livemap.ambethtyr.com/#/-249/64/242/-1/world%20-%20nether/ambethtyrnether)

**Comment by n4ru** [comment] 2019-04-25 15:41
Still occurs in 1.14

**Comment by supergnaw** [comment] 2019-06-09 07:12
It's June and this is still an issue.

**Comment by CounterPillow** [comment] 2019-06-11 01:36
@supergnaw so are you gonna fix it?

**Comment by supergnaw** [comment] 2019-06-11 02:46
Where in the code is the nether render mode? If I can look at how it's detecting the ceiling maybe I can modify it to ignore a single lava block that is surrounded netherrack.

**Comment by CounterPillow** [comment] 2019-06-11 03:14
https://github.com/overviewer/Minecraft-Overviewer/blob/master/overviewer_core/src/primitives/nether.c

**Comment by supergnaw** [comment] 2019-06-11 10:42
It clearly states block_lava so now I'm not sure what could be causing this. Is it possible that block_lava isn't actually the correct block? This requires further investigation because now it's gonna bug me.

**Comment by robosphinx** [comment] 2019-06-11 10:48
The Flattening (1.13+) seems to have renamed all lava variants (flowing/stationary) to "lava"

**Comment by supergnaw** [comment] 2019-06-11 13:03
so [the namespace id is supposedly just "lava"](https://minecraft.gamepedia.com/Lava/ID) rather than block_lava, but the roof is still removed with other items in the list appended to "block_" eg block_quartz_ore or block_bedrock. where is overviewer declaring these namespaces locally? maybe that's the source of the issue.

**Comment by robosphinx** [comment] 2019-06-11 22:35
Perhaps there's a relation between [the ID assigned in blockmap in world.py](https://github.com/overviewer/Minecraft-Overviewer/blob/522ee282192276dad70b1f00de7701db8f7fd105/overviewer_core/world.py#L325) (10) and [the ID in mc_id.h](https://github.com/overviewer/Minecraft-Overviewer/blob/522ee282192276dad70b1f00de7701db8f7fd105/overviewer_core/src/mc_id.h#L19) (11)?

**Comment by drnixon** [comment] 2019-09-10 17:49
Changing from 10 to 11 in world.py and rebuilding Overviewer seems to fix the hanging lava block issue. At least for the render I just ran.

**Comment by drnixon** [comment] 2019-09-10 17:56
Only potential issue I can see would be that the Overviewer then renders flowing blocks as if they were static, but looking back on old 1.12.2 renders I think it always did that anyway.

**Comment by supergnaw** [comment] 2019-11-01 20:51
@drnixon would you be able to draft up a quick guide on what exactly you did so I can replicate it?

**Comment by robosphinx** [comment] 2019-11-01 21:17
@supergnaw go to line 325 of world.py and replace 10 with 11
`'minecraft:lava': (11, 0),`

Confirmed to work across multiple renders on my 1.14.4 server.

**Comment by drnixon** [comment] 2019-11-04 17:49
> @drnixon would you be able to draft up a quick guide on what exactly you did so I can replicate it?

Exactly what robosphinx said on Nov 1. Just edited the single "minecraft:lava" line in world.py from (10, 0) to (11, 0) as a test based on robosphinx's Jun 11 comment, and it worked as expected.

**Comment by CounterPillow** [comment] 2020-02-14 19:48
I believe this is fixed now.

**Closed by CounterPillow** 2020-02-14 19:48 UTC
Labels: Minecraft 1.13, Needs Investigation, Rendermode
