### ISSUE TITLE
Google maps did not load correctly

### ISSUE THREAD

**Issue by ICEconchy** [overviewer/Minecraft-Overviewer#1371] opened 2017-03-11 13:34 UTC
Page didn't load google maps.

http://pasteboard.co/I8gMqeUW4.png

**Comment by Wruczek** [comment] 2017-03-11 15:03
Duplicate of #1308 
Current solution: https://github.com/overviewer/Minecraft-Overviewer/issues/1308#issuecomment-228310624
Or you can just wait for the leaflet version of Overviewer to come out.

**Comment by CounterPillow** [comment] 2017-03-11 16:40
Closed as duplicate.

We're working on it.

**Closed by CounterPillow** 2017-03-11 16:40 UTC
