### ISSUE TITLE
Display Biome in the X and Z coordinates area

### ISSUE THREAD

**Issue by MikeyCarter** [overviewer/Minecraft-Overviewer#1227] opened 2015-03-31 17:18 UTC
At the bottom where you display the X and Z coordinates.  Would be useful if you also displayed the biome type your hovering over too.

**Comment by LeadMagnet** [comment] 2015-04-01 09:39
+1

Also a config setting to change background and fore color and size while yer at it! :P

**Comment by CounterPillow** [comment] 2015-04-21 14:39
If I am correct, this would also require exporting lots biome information. I think simply using an overlay for this would be a better idea, since that already allows you to get biome information with block-level accuracy.

@LeadMagnet: Most HTML output styling options should not be done through the configuration file, but custom webassets. Wrapping every single bit of HTML output in some config options would be rather tedious and of questionable usefulness.

**Comment by LeadMagnet** [comment] 2015-04-21 15:53
Since the overlay is already available, yes I can see doing one, adding the biome data to the X/Y output box. (IE: X: 100 Y: 100 B: Extreme Hills) Unless I've missed something, there is no legend.

**Comment by CounterPillow** [comment] 2015-04-21 19:32
And how would you get the biome data for each coordinate? You'd have to save it somewhere. All overviewer generates is a bunch of tiles, viewing the map doesn't actually touch the world files, therefore we'd need to export biome information at render time. That would involve pretty much doing the same as the biome overlay already does, but simply presenting the data in a different way.

**Comment by MikeyCarter** [comment] 2015-04-21 20:11
Can you create multi-polygons for the biomes?   Or at the very least something to say what the colours mean?

**Comment by LeadMagnet** [comment] 2015-04-22 10:03
I'm new to the biome overlay feature so I'm not entirely sure how it works. However, I do know (from IRC conversations with you CP! :P ) that the overlay coloring is biome specific. The colors of the tile overlay are internally coded to be different for each biome.

Is there not a way to "tag" each tile with a biome "id" (int) that a mouseover event could check, relaying that to the positional data function in the corner?

Agreed, the biome overlay would be the best (and only) place to do this.

On the maps I am generating (http://188.165.162.243) I have one biome overlay. The players on the server do not know what this is showing because there is no legend saying "this color = this biome type". CP, your IRC suggestion to edit the source HTML to include this as a flyout menu is my only option so far. It's on my list of things to do! :P

BTW....have 2 IGN's...LeadMagnet and OldCrowExpress...for ref.

**Comment by CounterPillow** [comment] 2015-04-22 12:49
>Is there not a way to "tag" each tile with a biome "id" (int) that a mouseover event could check

You could abuse the PNG zTXT chunks to do this, but I'm not sure if browsers expose this information to JS. It would also not work for tiles further zoomed out unless you start doing some really funky things. And of course, JPEG would need that support too.

>The players on the server do not know what this is showing because there is no legend saying "this color = this biome type".

I'm also fairly certain that the biome overlay is probably outdated but I'd have to check on that. The thing is that including this as a mouse hover thing would be sort of hard.

A legend, however, might not be that bad of an idea. A lot of overlays use pretty arbitrary colour choices, so this is something to remember for the future.

**Comment by CounterPillow** [comment] 2015-04-30 16:25
Closing as this is a duplicate of #1060

**Closed by CounterPillow** 2015-04-30 16:25 UTC
