### ISSUE TITLE
RuntimeError

### ISSUE THREAD

**Issue by chinouvm** [overviewer/Minecraft-Overviewer#1881] opened 2020-12-13 20:02 UTC
When I run overviewer.exe --help I get:

https://gist.github.com/chinouvm/797578dddc6f22bc8771b22e87215d46

**Comment by Kikalino** [comment] 2020-12-14 18:50
Me too

**Comment by jmaximusix** [comment] 2020-12-19 08:39
Same here. After some googling i found that it seems to have to do with some bugs in Numpy 1.19.4, which overviewer seems to be using (see https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an). I haven't found a way do downgrade the numpy version integrated in the overviewer though (As 1.19.3 should work fine).
Sadly you can't download older versions of overviewer, bc overviewer 1.16.5 didn't seem to have these issues.

**Comment by Schafi68** [comment] 2020-12-22 19:52
Same issue here and after some research, i'm at the same point than @jmaximusix ...
Anybody have the previous win 64bits version to share ? :'( 
Or any fix/tips to downgrade Numpy in overviewer without compilating myself

**Comment by Kikalino** [comment] 2020-12-23 15:58
> Anybody have the previous win 64bits version to share ? :'(

http://www.noping.de/ov/overviewer-0.15.86.zip

I found Version 15.86 in my download directory.
This works for me.

**Comment by Schafi68** [comment] 2020-12-23 17:26
> 
> 
> > Anybody have the previous win 64bits version to share ? :'(
> 
> http://www.noping.de/ov/overviewer-0.15.86.zip
> 
> I found Version 15.86 in my download directory.
> This works for me.

Thanks a lot ! It seems to work !

**Comment by LevelZero-dev** [comment] 2020-12-30 17:02
> Same here. After some googling i found that it seems to have to do with some bugs in Numpy 1.19.4, which overviewer seems to be using (see https://stackoverflow.com/questions/64654805/how-do-you-fix-runtimeerror-package-fails-to-pass-a-sanity-check-for-numpy-an). 
It's actually not a bug in Numpy .. Numpy 1.19.4 added a check for a broken library implementation in Windows 10 v2004.
Currently, Microsoft has this scheduled to be fixed in late january. An insider preview build (# 20270) is now available which should contain this fix if you really can't wait.

Downgrading Numpy means that the code might not actually behave as intended on this version of Windows.

**Comment by jmaximusix** [comment] 2021-01-05 15:12
> It's actually not a bug in Numpy .. Numpy 1.19.4 added a check for a broken library implementation in Windows 10 v2004.
> Currently, Microsoft has this scheduled to be fixed in late january. An insider preview build (# 20270) is now available which should contain this fix if you really can't wait.
> 
> Downgrading Numpy means that the code might not actually behave as intended on this version of Windows.

I managed to compile it myself using python 3.7 and numpy 1.19.3. and it just works perfectly fine, but I'm glad to see this issue being solved officially soon

**Comment by CounterPillow** [comment] 2021-01-16 14:55
The rebuild I've just triggered by pushing to master should fix this issue, might take 30 minutes or so for all the builds to appear on the downloads page. Sorry for the long wait, and thank you for your patience.

**Closed by CounterPillow** 2021-01-16 14:55 UTC

**Comment by Schafi68** [comment] 2021-01-17 01:32
I've got this issue when downloading the windows 64 bits build fyi, false positive i suppose ? :s 
![image](https://user-images.githubusercontent.com/76495554/104828669-3000c080-586c-11eb-9a31-f57928789328.png)

**Comment by CounterPillow** [comment] 2021-01-17 04:22
Yes, it's a false-positive. Feel free to report it to your particular snakeoil vendor yourself, they all make it way too difficult and I've had enough of it when I reported a false-positive to Microsoft before.
