### ISSUE TITLE
WindowsError: [Error 183] File cannot be created if already exists, on --genpoi

### ISSUE THREAD

**Issue by JRSofty** [overviewer/Minecraft-Overviewer#1325] opened 2016-08-26 10:45 UTC
Running overviewer on Windows 7 x64. Everything is fine except when I attempt a --genpoi. When I do this I'm getting the following error:

2016-08-26 12:37:02 E An error has occurred. This may be a bug. Please let us kn
ow!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "overviewer.py", line 608, in <module>
  File "overviewer.py", line 130, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 540, in main
  File "overviewer_core\aux_files\genPOI.pyc", line 244, in save_cache
  File "overviewer_core\files.pyc", line 164, in **exit**
WindowsError: [Error 183] Eine Datei kann nicht erstellt werden, wenn sie bereit
s vorhanden ist

The German setting basically says that a file cannot be created because it already exists. This apparently was also mentioned and commented upon in a comment of another issue that doesn't seem related, thus the opening of this ticket.

Besides wiping my generated map and starting again fresh, what can I do to work around this problem until a fix for the atomic file renaming in Windows is taken fixed? What files does genpoi try to make that may already exist?

**Comment by CounterPillow** [comment] 2016-12-06 14:33
Duplicate of #1271

>What files does genpoi try to make that may already exist?

uuidcache.dat in the output folder.

**Closed by CounterPillow** 2016-12-06 14:33 UTC
