### ISSUE TITLE
Tiles not loading on map

### ISSUE THREAD

**Issue by pepoteloko** [overviewer/Minecraft-Overviewer#1322] opened 2016-08-18 06:45 UTC
I generate the map with overviewer without errors but when I open the web no tiles are loading.
I've check the folders and the images exists.
My POI's are generating well.

You can  see the map at: http://52.58.229.86/
And an example of generated tile: http://52.58.229.86/nit/3/0/0/0.png

I don't see any JS error.

**Comment by LeadMagnet** [comment] 2016-08-18 08:07
Can you post the config file you're using to [PasteBin](http://pastebin.com) or [CodePen ](http://codepen.io)so we can see targets.

**Comment by pepoteloko** [comment] 2016-08-18 09:32
Hi,

Here is my render config: http://pastebin.com/HQD9X3At

**Comment by CounterPillow** [comment] 2016-08-18 13:09
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

Gonna close this as a duplicate of #1308

**Closed by CounterPillow** 2016-08-18 13:09 UTC

**Comment by pepoteloko** [comment] 2016-08-18 21:06
I found the problem!

In overviewerConfig.js the base param was incorrect.
`"base": "{'createInfoWindow': True, 'filterFunction': <function baseFilter at 0x7f4863dd0c08>, 'name': 'Base Plain', 'checked': True, 'icon': 'icons/marker_base_plain.svg'}", `

I comment this line and the map work again and without api key.
I think my POIs are breaking the map...

Thanks!

**Comment by CounterPillow** [comment] 2016-08-19 00:01
Oh, hm, that's interesting

**Comment by pepoteloko** [comment] 2016-08-19 09:17
I delete the filter function 'baseFilter' from my config and stop rendering that POIs and now it works correctlly.

I think I use a name 'baseFilter' that is already used by overviewer and brake something :-P
