### ISSUE TITLE
How do i use my GPU to render?

### ISSUE THREAD

**Issue by Joemordecool** [overviewer/Minecraft-Overviewer#1919] opened 2021-04-27 18:51 UTC
The question its simple, i have a GPU and want to use it to render my world, i read the doc how to use it and the only thing about rendering its form the CPU, maybe doesn't support GPU yet but y want to know

**Comment by IncredibleHolg** [comment] 2021-04-28 09:52
Since most of the work is done by NumPy, this should apply:
https://stackoverflow.com/questions/49605231/does-numpy-automatically-detect-and-use-gpu
You may try this

**Comment by Joemordecool** [comment] 2021-04-28 12:29
Thank you, was so usefull, now i have to implement it haha

**Comment by CounterPillow** [comment] 2021-06-01 11:52
Closing as duplicate of #1506

**Closed by CounterPillow** 2021-06-01 11:52 UTC
