### ISSUE TITLE
Editing generated files

### ISSUE THREAD

**Issue by KaidenP** [overviewer/Minecraft-Overviewer#1368] opened 2017-03-03 05:33 UTC
Is it safe to edit the generated html files, specifically index.js and overviewerConfig.js?

I want to change the spawn point in my renders.

**Comment by CounterPillow** [comment] 2017-03-03 08:24
Overviewer rewrites them each time it renders, the recommended approach to modifying the HTML and JS files is to use custom webassets (see the documentation for more info about that).

As for overviewerConfig.js, that one is generated in assetmanager.py.

You can also simply disable the spawn marker altogether using the appropriate option for that, and use a manualpoi as a replacement wherever you want it.

**Comment by KaidenP** [comment] 2017-03-04 00:18
Well, I have 3 maps in one world. it always centers where the spawnpoint is in the entire world, And I would like it to center an a specific point when the user 1st loads the page.

**Comment by CounterPillow** [comment] 2017-03-13 18:17
>And I would like it to center an a specific point when the user 1st loads the page.

looks like a duplicate of #1350 then, closing.

**Closed by CounterPillow** 2017-03-13 18:17 UTC
