### ISSUE TITLE
Missing 1.14 blocks

### ISSUE THREAD

**Issue by Clayn** [overviewer/Minecraft-Overviewer#1613] opened 2019-07-18 07:49 UTC
Similar to #1560 the stairs for new slabs are missing.
Also Bamboo is missing in the overviewer map.  
In this image the roof is missing the red nether brick stairs

<img width="813" alt="grafik" src="https://user-images.githubusercontent.com/8006856/61439101-3180be00-a941-11e9-9d87-95850b938135.png">

**Comment by IncredibleHolg** [comment] 2019-07-26 15:06
Stairs should be easy to fix, sonce the textures are available.

Bamboo is someting different, since the texture is generated in game from  a json model using the multipart texture file. Similar problem as #1569

**Comment by IncredibleHolg** [comment] 2019-07-26 15:08
@Clayn Can you deliver a list containing the names of the missing blocks?

**Comment by Clayn** [comment] 2019-07-30 05:39
@IncredibleHolg Sure i will during the day.

**Comment by Clayn** [comment] 2019-07-30 13:48
Missing or Wrong Blocks (in the order they appear in the test map from west to east)

1. Spruce Sign 
2. Birch Sign
3. Jungle Sign
4. Acacia Sign
5. Dark Oak Sign
6. Stone Stairs and Slabs (seems they just use the wron texture=
7. Brick Wall
10. Granite Stairs & Wall
11. Polished granite Stairs
12. Diorite Stairs & Wall
13. Polished diorite Stairs
14. Andesite Wall
15. Polished andesite Stairs
16. Sandstone Wall
17. Red sandstone Wall
18. Smooth Quarz Stairs
19. Prismarin Walls
22. Netherbrick Walls
23. Red Netherbrick Stairs & Walls
24. Endstone Brick Stairs & Wallds
26. Barrels (different directions)
27. Scaffolding
28. Bell
29. Campfire
30. Composter
31. Lantern
32. Lectern (using bottom texture of the bookshelf i guess)
34. Grindstone (rendered incorrectly)
36. Stonecutter different directions (only rendering the bottom half)
38. Bamboo
39. Cornflower
40. Wither Rose
41. Lilly of the Valley

![grafik](https://user-images.githubusercontent.com/8006856/62134809-71e92000-b2e1-11e9-8d3b-718c885028e9.png)


![2019-07-30_15 46 37](https://user-images.githubusercontent.com/8006856/62134772-672e8b00-b2e1-11e9-9378-efc353024fc6.png)
![2019-07-30_15 46 41](https://user-images.githubusercontent.com/8006856/62134773-672e8b00-b2e1-11e9-95a1-d1eb5ac6c3b6.png)
![2019-07-30_15 46 45](https://user-images.githubusercontent.com/8006856/62134775-672e8b00-b2e1-11e9-9833-863ba875ab47.png)
![2019-07-30_15 46 51](https://user-images.githubusercontent.com/8006856/62134779-672e8b00-b2e1-11e9-9894-d819c6ad9e31.png)

**Comment by IncredibleHolg** [comment] 2019-08-03 09:27
* [ ]    Stone Stairs and Slabs (seems they just use the wrong texture
* [ ]    Smooth Quarz Stairs
* [ ]    Polished granite Stairs
* [ ]    Polished diorite Stairs
* [ ]    Granite Stairs
* [ ]    Diorite Stairs
* [ ]    Polished andesite Stairs
* [ ]    Red Netherbrick Stairs
* [ ]    Endstone Brick Stairs
* [ ]    Spruce Sign
* [ ]    Birch Sign
* [ ]    Jungle Sign
* [ ]    Acacia Sign
* [ ]    Dark Oak Sign
* [ ]    Brick Wall
* [ ]    Granite Wall
* [ ]    Diorite Wall
* [ ]    Andesite Wall
* [ ]    Sandstone Wall
* [ ]    Red sandstone Wall
* [ ]    Prismarin Walls
* [ ]    Netherbrick Walls
* [ ]    Red Netherbrick Walls
* [ ]    Endstone Brick Walls
* [ ]    Barrels (different directions)
* [ ]    Scaffolding
* [ ]    Bell
* [ ]    Campfire
* [ ]    Composter
* [ ]    Lantern
* [ ]    Lectern (using bottom texture of the bookshelf i guess)
* [ ]    Grindstone (rendered incorrectly)
* [ ]    Stonecutter different directions (only rendering the bottom half)
* [ ]    Bamboo
* [ ]    Cornflower
* [ ]    Wither Rose
* [ ]    Lilly of the Valley

**Comment by IncredibleHolg** [comment] 2019-08-03 09:27
Lantern is done with #1617

**Comment by IncredibleHolg** [comment] 2019-08-03 11:02
Working on my fork:

[https://github.com/IncredibleHolg/Minecraft-Overviewer/tree/114stairs](https://github.com/IncredibleHolg/Minecraft-Overviewer/tree/114stairs) ```d301a34```

Fixed stone slabs and stairs ( collision with the legacy naming for stairs cleared up)

**Comment by IncredibleHolg** [comment] 2019-08-03 11:03
![stone_stairs_slabs01](https://user-images.githubusercontent.com/41533138/62411107-17a4d380-b5ef-11e9-8844-dfd17bb63ee5.png)

![stone_stairs_slabs02](https://user-images.githubusercontent.com/41533138/62411109-1d021e00-b5ef-11e9-8c48-da01766a2815.png)

**Comment by IncredibleHolg** [comment] 2019-08-03 11:05
Looking at the Image, the coblestone stair is now broken ...

**Comment by IncredibleHolg** [comment] 2019-08-03 12:29
![stone_stairs_slabs03](https://user-images.githubusercontent.com/41533138/62411931-18436700-b5fb-11e9-8561-6c5da225cc88.png)

OK works as expected now

**Comment by IncredibleHolg** [comment] 2019-08-03 18:39
The smooth quartz stairs do not have a simple texture, the texture is defined using the 
blockstate json:

```json
{
    "variants": {
        "facing=east,half=bottom,shape=straight":  { "model": "block/smooth_quartz_stairs" },
        "facing=west,half=bottom,shape=straight":  { "model": "block/smooth_quartz_stairs", "y": 180, "uvlock": true },
        "facing=south,half=bottom,shape=straight": { "model": "block/smooth_quartz_stairs", "y": 90, "uvlock": true },
        "facing=north,half=bottom,shape=straight": { "model": "block/smooth_quartz_stairs", "y": 270, "uvlock": true },
        "facing=east,half=bottom,shape=outer_right":  { "model": "block/smooth_quartz_stairs_outer" },
        "facing=west,half=bottom,shape=outer_right":  { "model": "block/smooth_quartz_stairs_outer", "y": 180, "uvlock": true },
        "facing=south,half=bottom,shape=outer_right": { "model": "block/smooth_quartz_stairs_outer", "y": 90, "uvlock": true },
        "facing=north,half=bottom,shape=outer_right": { "model": "block/smooth_quartz_stairs_outer", "y": 270, "uvlock": true },
        "facing=east,half=bottom,shape=outer_left":  { "model": "block/smooth_quartz_stairs_outer", "y": 270, "uvlock":a true },
        "facing=west,half=bottom,shape=outer_left":  { "model": "block/smooth_quartz_stairs_outer", "y": 90, "uvlock": true },
        "facing=south,half=bottom,shape=outer_left": { "model": "block/smooth_quartz_stairs_outer" },
        "facing=north,half=bottom,shape=outer_left": { "model": "block/smooth_quartz_stairs_outer", "y": 180, "uvlock": true },
        "facing=east,half=bottom,shape=inner_right":  { "model": "block/smooth_quartz_stairs_inner" },
        "facing=west,half=bottom,shape=inner_right":  { "model": "block/smooth_quartz_stairs_inner", "y": 180, "uvlock": true },
        "facing=south,half=bottom,shape=inner_right": { "model": "block/smooth_quartz_stairs_inner", "y": 90, "uvlock": true },
        "facing=north,half=bottom,shape=inner_right": { "model": "block/smooth_quartz_stairs_inner", "y": 270, "uvlock": true },
        "facing=east,half=bottom,shape=inner_left":  { "model": "block/smooth_quartz_stairs_inner", "y": 270, "uvlock": true },
        "facing=west,half=bottom,shape=inner_left":  { "model": "block/smooth_quartz_stairs_inner", "y": 90, "uvlock": true },
        "facing=south,half=bottom,shape=inner_left": { "model": "block/smooth_quartz_stairs_inner" },
        "facing=north,half=bottom,shape=inner_left": { "model": "block/smooth_quartz_stairs_inner", "y": 180, "uvlock": true },
        "facing=east,half=top,shape=straight":  { "model": "block/smooth_quartz_stairs", "x": 180, "uvlock": true },
        "facing=west,half=top,shape=straight":  { "model": "block/smooth_quartz_stairs", "x": 180, "y": 180, "uvlock": true },
        "facing=south,half=top,shape=straight": { "model": "block/smooth_quartz_stairs", "x": 180, "y": 90, "uvlock": true },
        "facing=north,half=top,shape=straight": { "model": "block/smooth_quartz_stairs", "x": 180, "y": 270, "uvlock": true },
        "facing=east,half=top,shape=outer_right":  { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 90, "uvlock": true },
        "facing=west,half=top,shape=outer_right":  { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 270, "uvlock": true },
        "facing=south,half=top,shape=outer_right": { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 180, "uvlock": true },
        "facing=north,half=top,shape=outer_right": { "model": "block/smooth_quartz_stairs_outer", "x": 180, "uvlock": true },
        "facing=east,half=top,shape=outer_left":  { "model": "block/smooth_quartz_stairs_outer", "x": 180, "uvlock": true },
        "facing=west,half=top,shape=outer_left":  { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 180, "uvlock": true },
        "facing=south,half=top,shape=outer_left": { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 90, "uvlock": true },
        "facing=north,half=top,shape=outer_left": { "model": "block/smooth_quartz_stairs_outer", "x": 180, "y": 270, "uvlock": true },
        "facing=east,half=top,shape=inner_right":  { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 90, "uvlock": true },
        "facing=west,half=top,shape=inner_right":  { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 270, "uvlock": true },
        "facing=south,half=top,shape=inner_right": { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 180, "uvlock": true },
        "facing=north,half=top,shape=inner_right": { "model": "block/smooth_quartz_stairs_inner", "x": 180, "uvlock": true },
        "facing=east,half=top,shape=inner_left":  { "model": "block/smooth_quartz_stairs_inner", "x": 180, "uvlock": true },
        "facing=west,half=top,shape=inner_left":  { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 180, "uvlock": true },
        "facing=south,half=top,shape=inner_left": { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 90, "uvlock": true },
        "facing=north,half=top,shape=inner_left": { "model": "block/smooth_quartz_stairs_inner", "x": 180, "y": 270, "uvlock": true }
    }
}
```

@Clayn 
I suggest to use the quartz stair texture, since the difference between this textures is only the border pixels, which will be hardly visible in maximum zoom of the overviewer-

**Comment by IncredibleHolg** [comment] 2019-08-03 18:48
![quartz001](https://user-images.githubusercontent.com/41533138/62415812-092adc00-b630-11e9-9605-d21824b0b65c.png)

![quartz002](https://user-images.githubusercontent.com/41533138/62415815-10ea8080-b630-11e9-80c3-530066111900.png)

**Comment by IncredibleHolg** [comment] 2019-08-04 07:14
New polished stairs

![polished-stairs-new001](https://user-images.githubusercontent.com/41533138/62420763-26939080-b698-11e9-88cb-0455f779c984.png)

**Comment by IncredibleHolg** [comment] 2019-08-04 07:45
https://github.com/IncredibleHolg/Minecraft-Overviewer/commit/04f2672c4cad0709ec1a6557065f30156ff7645b 
![polished-stairs-new002](https://user-images.githubusercontent.com/41533138/62421092-973cac00-b69c-11e9-8439-3bef573b822b.png)

**Comment by mtoensing** [comment] 2019-08-06 10:25
+1 for Andesite Wall

**Comment by rveachkc** [comment] 2019-08-07 16:13
**Smooth Sandstone Stairs** also appear to be missing.

**Comment by IncredibleHolg** [comment] 2019-08-09 06:33
Missing stairs implemented , code  and  commits need some cleanup, 
pull request will be ready probably tomorrow.
![more-stairs001](https://user-images.githubusercontent.com/41533138/62758995-579d0800-ba80-11e9-9ffb-b8114b212299.png)

![more-stairs002](https://user-images.githubusercontent.com/41533138/62759009-5ff54300-ba80-11e9-8006-c4b99512e29c.png)

**Comment by IncredibleHolg** [comment] 2019-08-10 09:28
Pull request #1624 1624 created

**Comment by Gyzie** [comment] 2019-08-16 12:40
I've added the missing signs in pull request #1627 

![afbeelding](https://user-images.githubusercontent.com/8080706/63168181-bbe93a00-c033-11e9-9d70-3b128e6d7105.png)

**Comment by Gyzie** [comment] 2019-08-16 13:25
Added bamboo saplings in pull request #1628 (Not the bamboo itself, only the sapling)
![afbeelding](https://user-images.githubusercontent.com/8080706/63170664-11c0e080-c03a-11e9-99dc-f9058d0650a1.png)

**Comment by IncredibleHolg** [comment] 2019-08-21 06:04
Working on stone walls
![stonefences_00](https://user-images.githubusercontent.com/41533138/63406472-4b9f3780-c3ea-11e9-9696-e190c9972a8a.png)

![stonefences_01](https://user-images.githubusercontent.com/41533138/63406476-51951880-c3ea-11e9-9f7f-f2235e535878.png)

**Comment by IncredibleHolg** [comment] 2019-08-21 06:17
Pull request  #1633  created

**Comment by Dravere** [comment] 2019-08-31 16:47
Went ahead and added scaffolding. Created pull request #1640.

![](https://user-images.githubusercontent.com/2047920/64066842-32369080-cc1f-11e9-9013-347775a4cd99.png)

**Comment by CrowMash** [comment] 2019-09-02 06:18
Looks like Sweet Berry Bushes are missing too (all four stages).

**Comment by IncredibleHolg** [comment] 2019-10-15 07:48
Merged the pull requests #1640 and #1633

![merge-scaffolding](https://user-images.githubusercontent.com/41533138/66811141-defb7180-ef30-11e9-8fda-3114aa077438.png)

**Comment by IncredibleHolg** [comment] 2019-10-15 07:55
@Dravere I merged your pull request and  my dtone wall upadate into #1660

**Comment by Clayn** [comment] 2019-10-19 06:43
Just noticed that red sandstone stairs are missing as well.

**Comment by bagobones** [comment] 2019-10-20 21:01
Unless it is a known issue you may want to add doors to the list.. I seem to be missing most door types and some of the ones that are rendering are backwards in terms of inside / outside. Not sure if this is a 1.14 specific issue.

**Comment by IncredibleHolg** [comment] 2019-10-27 07:45
@Clayn 
confirmed the missing red sandstone stair.
@bagobones 
check the version you are refering to. This discussion references development branches, containing many blocks not present in the main branch.
![stairs+doors-001](https://user-images.githubusercontent.com/41533138/67631379-e0645c80-f895-11e9-873b-addf2e927caf.png)

**Comment by IncredibleHolg** [comment] 2019-10-27 10:53
* Closed the prevous pull request.
* added pull requies #1664

**Comment by IncredibleHolg** [comment] 2019-10-27 11:22
Changes are now in master branch 
![stairs+doors-002](https://user-images.githubusercontent.com/41533138/67633766-55df2580-f8b4-11e9-888a-a251aa1c3695.png)

**Comment by IncredibleHolg** [comment] 2019-10-27 11:41
Bamboo sapling is in, the bamboo stalk uses a json file to crete the texture.

The needed parts in assets/minecraft/textures/block/bamboo_stalk.png look like this:

![bamboo-side](https://user-images.githubusercontent.com/41533138/67633987-0817ec80-f8b7-11e9-827a-a6f8c2f2cad7.png)

![bamboo-bottom](https://user-images.githubusercontent.com/41533138/67633991-0cdca080-f8b7-11e9-9050-b081f8405ec6.png)

![bamboo-top](https://user-images.githubusercontent.com/41533138/67633993-1108be00-f8b7-11e9-83ef-d6f6f787c0de.png)

**Comment by CounterPillow** [comment] 2019-10-27 11:46
we really ought to add a block model renderer already lol

**Comment by IncredibleHolg** [comment] 2019-11-01 06:37
Will add bamboo and composter from #1666

**Comment by IncredibleHolg** [comment] 2019-11-01 10:47
Bamboo and composter added #1668

**Comment by IncredibleHolg** [comment] 2019-11-01 10:54
![bamboo+composter](https://user-images.githubusercontent.com/41533138/68020276-4b4ed280-fc9e-11e9-995e-002d6ea94fe7.png)

**Comment by IncredibleHolg** [comment] 2019-11-25 17:10
@CounterPillow 
Hi,
before I go on adding the last missing blocks, could jou pull #1668 ?

last missing blocks:

* [ ]    Bell
* [ ]    Campfire
* [ ]    Lectern (using bottom texture of the bookshelf i guess)
* [ ]    Grindstone (rendered incorrectly)
* [ ]    Stonecutter different directions (only rendering the bottom half)
* [ ]    Cornflower
* [ ]    Wither Rose
* [ ]    Lilly of the Valley

**Comment by CounterPillow** [comment] 2019-11-26 01:27
@IncredibleHolg I'll try to get around to it when I have the time this week.

**Comment by IncredibleHolg** [comment] 2019-12-07 08:11
Stared by adding new flowers
![newflowers](https://user-images.githubusercontent.com/41533138/70371300-95485b00-18d1-11ea-96c3-654aec6a1f44.png)

**Comment by IncredibleHolg** [comment] 2019-12-07 08:35
The bell renders in three variants, adding oriantation to the hanging versions
* 'attachment': 'floor'
* 'attachment': 'ceiling', 'facing' north, east, south, west
* 'attachment': 'double_wall', 'facing' north, east, south, west

**Comment by Kaemmelot** [comment] 2020-05-01 15:31
@IncredibleHolg As mentioned [before](#issuecomment-527016978), your list misses the sweet berry bushes.
- [ ] Sweet Berry Bush
and also the
- [ ] Jigsaw Block (technical block, only cheatable, _but_ visible)

There are more blocks that are rendered, but don't seem to keep the orientation in mind:

- [ ] Blast Furnance
- [ ] Smoker
- [ ] Loom

**Comment by tifkat** [comment] 2020-06-07 15:09
Another vote for sweet berry bushes

**Comment by IncredibleHolg** [comment] 2020-06-13 10:53
OK, implementing sweet berry bushes.
The number of block states is four, according to 

https://minecraft.gamepedia.com/Sweet_Berries#Block_states 

The crops already implemented have 8 data values, even if only four of them are used.
So we cannot expand the crops4 function but have to write a new **crops_actual4**

**Comment by IncredibleHolg** [comment] 2020-06-13 12:31
WIP: sweet_berry, Cornflower,Wither Rose and Lilly of the Valley

![flowers_and_berries01](https://user-images.githubusercontent.com/41533138/84568840-9677aa80-ad82-11ea-83f5-183dc0e22df8.png)

![flowers_and_berries02](https://user-images.githubusercontent.com/41533138/84568844-9b3c5e80-ad82-11ea-9c53-8d1ca92b539e.png)

**Comment by IncredibleHolg** [comment] 2020-06-13 14:59
created pull request #1786

**Comment by marvasDE** [comment] 2020-06-19 14:26
I would realy like to see some campfires. Especially if they are extinguished, because many people use this for decorative grounds (e.g. bridges, docks, ...)

![mc-bridge](https://user-images.githubusercontent.com/12934302/85143085-96c3ea00-b249-11ea-8a80-f68be83e9bf4.png)

**Comment by IncredibleHolg** [comment] 2020-06-20 09:09
The texture is generated from ``campfire.json`` and ``campfire_off.json`` while the texture file contains only the needed sub-textures

![campfire_log](https://user-images.githubusercontent.com/41533138/85198076-04bdef00-b2e6-11ea-885c-7cc943973ed5.png)
 Implementing this requires rebuilding the texture from the JSON file.

**Comment by Auron956** [comment] 2020-06-22 01:31
I implemented campfires along with some other blocks mentioned in this issue a while ago but haven't got around to creating a pull request yet, will try to do that tomorrow.
![firefox_mWGUEysuJx](https://user-images.githubusercontent.com/2823982/85239115-1b6d5e80-b42a-11ea-90b1-cde480c27267.png)

**Comment by IncredibleHolg** [comment] 2020-06-24 13:48
@Auron956 excellent job!

**Comment by IncredibleHolg** [comment] 2020-06-24 15:28
@Clayn I think the issue can be closed now, since @Auron956  added the last missing blocks.

The blocks of 1.16 should be handled in another issue.

**Comment by CounterPillow** [comment] 2020-06-24 16:08
Closing this since 1.14 blocks seem to all be there now.

**Closed by CounterPillow** 2020-06-24 16:08 UTC
