### ISSUE TITLE
Overviewer 0.13.76 cannot find MC 1.14 textures

### ISSUE THREAD

**Issue by ravennst** [overviewer/Minecraft-Overviewer#1557] opened 2019-04-24 04:25 UTC
Overviewer 0.13.76 cannot find MC 1.14 textures. Even pointing the texturepath flag to the 1.14.jar flag doesn't work. I had to point the texturepath to the 1.13.2.jar to get the map to render.

**Comment by beeradmoore** [comment] 2019-04-25 08:42
I did not expect this to be 1.14 compatible a week within launch and this post gave me hope. But setting texture path to the client 1.13.2.jar didn't work for me. Gave error, 

2019-04-25 18:38:41 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help


> $ overviewer.py --check-tiles --config=render.conf
> 2019-04-25 18:38:40  Welcome to Minecraft Overviewer!
> 2019-04-25 18:38:40  Checking all tiles for updates manually.
> 2019-04-25 18:38:40  Generating textures...
> 2019-04-25 18:38:41 E An error has occurred. This may be a bug. Please let us know!
> See http://docs.overviewer.org/en/latest/index.html#help
> 
> This is the error that occurred:
> Traceback (most recent call last):
>   File "/usr/bin/overviewer.py", line 637, in <module>
>     ret = main()
>   File "/usr/bin/overviewer.py", line 489, in main
>     tex.generate()
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 103, in generate
>     tex = texgen(self, blockid, data)
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 854, in func_wrapper
>     return func(texobj, blockid, data)
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 1013, in no_inner_surfaces
>     texture = self.load_water()
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 352, in load_water
>     watertexture = self.load_image("custom_water_still.png")
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 336, in load_image
>     fileobj = self.find_file(filename)
>   File "/usr/lib/python2.7/dist-packages/overviewer_core/textures.py", line 281, in find_file
>     jar = zipfile.ZipFile(jarpath)
>   File "/usr/lib/python2.7/zipfile.py", line 770, in __init__
>     self._RealGetContents()
>   File "/usr/lib/python2.7/zipfile.py", line 813, in _RealGetContents
>     raise BadZipfile, "File is not a zip file"
> BadZipfile: File is not a zip file
> 


And that is with the same version AFAIK.

> $ overviewer.py --version
> Minecraft Overviewer 0.13.76 (8760b04)
> built on Tue Apr 23 12:05:59 2019
>

**Comment by CounterPillow** [comment] 2019-04-25 13:17
@beeradmoore your downloaded .jar seems to have been corrupt.

**Comment by beeradmoore** [comment] 2019-04-25 21:15
@CounterPillow hash was correct, and I’m still pointing to the same file from my config. If comment out the texturepath line (assuming it uses system defaults) or doesn’t work either.

**Comment by CounterPillow** [comment] 2019-04-26 01:29
@beeradmoore I've just manually downloaded the 1.13.2 textures jar from https://overviewer.org/textures/1.13.2 (which just redirects to the appropriate Mojang download URL), then placed it in a directory, then pointed texturespath to said file, then renamed my .minecraft to make sure overviewer wasn't picking it up and ran the latest overviewer, and it works fine.

So either you:
- found a bug in the Python standard library that makes it not recognise perfectly valid zip files only on your system, and only if the client is in a specific path, ***or***
- you messed up somewhere.

The odds are not in your favour here, but if you want to you can try to open a python2 shell and go

```
>>>from zipfile import ZipFile
>>>z = ZipFile("/the/jar/not/working/here.jar")
```

If that throws a BadZipFile error, then it's not our fault. If that doesn't throw a BadZipFile error, then I'm going to need your actual full config and the file in question as well as what OS you're on.

-------

The actual issue with Overviewer not recognising the 1.14 jar is that Mojang renamed `stone_slab_side.png` to `smooth_stone_slab_side.png` and `stone_slab_top.png` to `smooth_stone.png`. I'll get around to fixing it and bumping the textures requirements as well as the CI and such when I've had some sleep.

**Comment by beeradmoore** [comment] 2019-04-26 01:56
```
 $ python
 Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
 [GCC 6.3.0 20170516] on linux2
 Type "help", "copyright", "credits" or "license" for more information.
 >>> from zipfile import ZipFile
 >>> z = ZipFile("/home/roxbox/Desktop/Minecraft/Versions/1.13.2.jar")
 >>> 
```

This appears to have worked fine. 

This is the script I used to download Minecraft, https://gist.github.com/beeradmoore/1f0cf78e8b8dec624d65276bb9915be8

OS is Debian 9.8. Overviewer is installed via apt, although I had built from source for the world113 branch at some point. This machine was previously rendering Minecraft 1.13 worlds fine. I had Minecraft launcher installed but the launcher would not open. I got the latest download from the Minecraft site and attempted to install like they said,

> sudo apt-get install Minecraft.deb

I now had dependency issues which I had to fix with 

> sudo apt --fix-broken install

After that trying to install Minecraft.deb told me it was already the latest version. Launcher now worked and I was able to install the 1.13.2 and 1.14 clients via the launcher.

I don't recall the modules installed with the dependency fix, but allegedly an installed copy of Minecraft is not required if I have the client jars downloaded. I don't know if fixing the dependency or installing the clients fixed the issue as I didn't run overviewer between those two instances. I didn't change overviewer config between it not working and it working.

Here is my current config.

```
def signFilter(poi):
    if poi["id"] == "Sign":
        return " \n".join([poi["Text1"], poi["Text2"],
                           poi["Text3"], poi["Text4"]])

def playerFilter(poi):
    if poi["id"] == "Player":
        poi['icon'] = "http://overviewer.org/avatar/%s" % poi['EntityId']
	info = "[%s] \n %s \n" % (poi["id"], poi["EntityId"])
        return info
    elif poi["id"] == "PlayerSpawn":
        poi['icon'] = "bed.png"
        return "[%s] \n %s \n" % (poi["id"], poi["EntityId"])

signs = {'name': "Signs", 'filterFunction': signFilter}
players = {'name': "Players", 'filterFunction': playerFilter, 'checked': True}



worlds["OneFourteenServer"] = "~/Desktop/Minecraft/OneFourteenServer/world"


renders["OneFourteenServerDay"] = {
    "world": "OneFourteenServer",
    "title": "Day",
    "rendermode": smooth_lighting,
    "dimension": "overworld",
    "markers": [players],
}


renders["OneFourteenServerNight"] = {
    "world": "OneFourteenServer",
    "title": "Night",
    "rendermode": smooth_night,
    "dimension": "overworld",
    "markers": [players],
}



processes=4
#texturepath = "/home/roxbox/Desktop/Minecraft/Versions/minecraft_client.1.14.jar"
texturepath = "/home/roxbox/Desktop/Minecraft/Versions/minecraft_client.1.13.2.jar"
outputdir = "/var/www/html/mcmap"

```

**Comment by CounterPillow** [comment] 2019-04-26 02:07
@beeradmoore `/home/roxbox/Desktop/Minecraft/Versions/minecraft_client.1.13.2.jar` and `/home/roxbox/Desktop/Minecraft/Versions/1.13.2.jar` are not the same file. Which one was not working when you pointed the texturepath at it?

And you're saying it suddenly started working out of the blue, without changing your texturepath? Overviewer will fall back to a system client jar if the one specified in texturepath doesn't work. However, if you run with that config and `--check-terrain`, we should see what Overviewer is searching and giving up on. I'm guessing you had some corrupt jar that Overviewer tried to fall back on, and now no longer have it.

But either way it's an unrelated issue and off-topic here.

**Comment by CounterPillow** [comment] 2019-04-26 02:20
The original issue has been fixed in e25557d257ea52c099168d0d6267d7c66178c274.

**Closed by CounterPillow** 2019-04-26 02:20 UTC

**Comment by beeradmoore** [comment] 2019-04-26 02:28
I have two copies of the exact same file that I got from different places (one via my download script, one via reading the json manually and getting the download URL). Please check your attitude at the door, I'm here giving my time to give plenty of information to debug a potential issue with these tools.

```
$ cksum 1.13.2.jar 
2984149942 16089640 1.13.2.jar
$ python
Python 2.7.13 (default, Sep 26 2018, 18:42:22) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from zipfile import ZipFile
>>> z = ZipFile("/home/roxbox/Desktop/Minecraft/Versions/minecraft_client.1.13.2.jar")
>>> z = ZipFile("/home/roxbox/Desktop/Minecraft/Versions/1.13.2.jar")
>>> 
```

Rendering was done with
```
overviewer.py --check-tiles --config=render.conf
```

If I do a 
```
overviewer.py --check-tiles --check-terrain --config=render.conf
```
I can see it giving a bunch of 
```
2019-04-26 12:13:54  Found assets/minecraft/textures/block/sandstone_top.png in '/home/roxbox/Desktop/Minecraft/Versions/minecraft_client.1.13.2.jar'
```
so it is using the same file from the config as expected. But this is now with a system which is fixed so I can't really tell you what the problem was before that.

No it didn't suddenly work out of the blue, it suddenly worked once I got the Minecraft launcher again which makes no sense because the config was never changed and it should be using that regardless if the default install was somehow corrupt.

I got the apt history, this is what was installed with the --fix-broken
```
Start-Date: 2019-04-25  18:55:07
Commandline: apt --fix-broken install
Requested-By: roxbox (1000)
Install: gconf2-common:amd64 (3.2.6-4, automatic), libpangox-1.0-0:amd64 (0.0.2-5+b2, automatic), libpango1.0-0:amd64 (1.40.5-1, automatic), gconf-service:amd64 (3.2.6-4+b1, automatic), libgconf-2-4:amd64 (3.2.6-4+b1, automatic)
End-Date: 2019-04-25  18:55:11
```
Not sure if they shed any light on why it wasn't working. I tried to uninstall these packages but it wants to remove minecraft-launcher, which won't put the system back in the previous state as I did have minecraft-launcher installed but somehow the others were messed up. Regardless I removed them all and was unable to replicate the issue.

It originally seemed like a related issue, but I agree this is now untreated and off topic. I am happy to put it down to my system being in a funky state even though a corrupt Minecraft install shouldn't prevent it working when we have it pointed to a standalone client jar file.

**Comment by CounterPillow** [comment] 2019-04-26 02:33
>so it is using the same file from the config as expected. But this is now with a system which is fixed so I can't really tell you what the problem was before that.

If you can't reproduce it then we can't really debug it.

>Please check your attitude at the door, I'm here giving my time to give plenty of information to debug a potential issue with these tools.

Thanks but I don't need help flooding issues with unrelated gripes about unreproducible exceptions.

>even though a corrupt Minecraft install shouldn't prevent it working when we have it pointed to a standalone client jar file.

As far as I'm aware, it doesn't. It tries them in order

1. manually specified texture path
2. something in the overviewer directory
3. minecraft install
