### ISSUE TITLE
Error generating textures: Could not find texture (...)

### ISSUE THREAD

**Issue by ElEd0** [overviewer/Minecraft-Overviewer#1410] opened 2017-09-03 21:52 UTC
I cant get the overviewer to work, whenever I try to render a world I get the following error message:

> E Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.10-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

-I've checked and I indeed have the texture in all of my installed versions, I dont have a clue of why is this happening.
-I have installed all the 1.10 versions, the last version (1.12.1) and the version I play in (1.8) but still it cant find the texture
-My .minecraft folder is in the default directory
-Running overviewer version 0.12.137, which I believe is the last one
-I've done many renders in the past without any problem, this is the first time I've ever had a similar error.

As the program says, I've also tried to use a configuration file with the texturepath option pointing to a full assets folder, but even then it fails to find the bed texture.

**Comment by CounterPillow** [comment] 2017-09-03 21:56
>Running overviewer version 0.12.137, which I believe is the last one

There's your problem, your Overviewer is out of date, because Windows builds are out of date.

If you play on 1.8, you can try explicitly setting texturepath to the 1.8 jar to work around this.

Duplicate of #1390

**Closed by CounterPillow** 2017-09-03 21:56 UTC

**Comment by agrif** [comment] 2017-09-03 23:55
You could also download a recent-ish windows build here:

http://static-backend.overviewer.org/builds/master/861/

It hasn't been plumbed in to our downloads page, but it should work.
