### ISSUE TITLE
ModuleNotFoundError: No module named 'overviewer-core'

### ISSUE THREAD

**Issue by philip107777** [overviewer/Minecraft-Overviewer#1678] opened 2019-11-16 23:47 UTC
So I just went to install Overviewer on my machine, I'm running Ubuntu 18 and I downloaded it to the /ect/apt file like told. And then I tried to run this command from that same directory and got this error. I tried to then go to the same directory as my Server, reinstall the Overviewer files and run the command again to get the same error. This is all it gave me:

`philip@philip-barn-PC:~/Desktop/Mc Server 1.14.4$ overviewer.py "My World" /home/username/mcmap
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 38, in <module>
    from overviewer_core import util
ModuleNotFoundError: No module named 'overviewer_core'`

**Comment by CounterPillow** [comment] 2019-11-16 23:53
Duplicate of https://github.com/overviewer/Minecraft-Overviewer/issues/1595

**Closed by CounterPillow** 2019-11-16 23:54 UTC
