### ISSUE TITLE
[overviewer-0.12-280] [Windows] POIs migrate to bottom of map on zoom out

### ISSUE THREAD

**Issue by durand1w** [overviewer/Minecraft-Overviewer#1516] opened 2019-02-21 00:49 UTC
I'm not sure if this is a known issue or an easy config fix.  For the 1.12 world that I have scanned, I have added manual POIs to the file and generated them successfully.  However, when the map is zoomed out the POIs appear at the bottom of the map beyond the world borders.  Each zoom in they correct more toward their locations.  They are only correct on the highest zoom in level.

If anyone has any ideas or suggestions, please let me know.  Build 333 appears to require 1.13 textures, so I have not been able to validate if it has the fix for this specific issue.

**Comment by CounterPillow** [comment] 2019-02-21 01:16
duplicate of #1481

**Closed by CounterPillow** 2019-02-21 01:16 UTC
