### ISSUE TITLE
IndexError after updating to Minecraft 1.16.1

### ISSUE THREAD

**Issue by ToastyBreadMan** [overviewer/Minecraft-Overviewer#1797] opened 2020-07-01 21:28 UTC
I updated to Minecraft 1.16.1 I have been having renders fail on a specific chunk in my world, causing the process to hang and the render to fail. I built the newest release of Overviewer [27eabb0](https://github.com/overviewer/Minecraft-Overviewer/commit/27eabb08a55d5b13e70bd5a425d31b246f361be7), and the problem is still persisting.  

This is the error that I am seeing.
```
tbm@mcserver:~/Minecraft-Overviewer$ ./overviewer.py -c test.config
2020-07-01 17:07:01  Welcome to Minecraft Overviewer version 0.15.81 (27eabb0)!
2020-07-01 17:07:01  Generating textures...
2020-07-01 17:07:20  Preprocessing...
2020-07-01 17:08:18  Rendering 79144 total tiles.
2020-07-01 17:14:13 E Could not render chunk 16,46 for some reason. This is likely a render primitive option error. 2343 6.64t/s eta 03h 12m 5
2020-07-01 17:14:13 E Full error was:
Traceback (most recent call last):
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/tileset.py", line 1091, in _render_rendertile
    c_overviewer.render_loop(
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1788, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1461, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1278, in _get_blockdata_v113
    blocks[:] = translated_blocks[block_states]
IndexError: index 28 is out of bounds for axis 0 with size 28
2020-07-01 17:14:16 E Could not render chunk 16,46 for some reason. This is likely a render primitive option error.
2020-07-01 17:14:16 E Full error was:
Traceback (most recent call last):
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/tileset.py", line 1091, in _render_rendertile
    c_overviewer.render_loop(
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1788, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1461, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/home/tbm/Minecraft-Overviewer/overviewer_core/world.py", line 1278, in _get_blockdata_v113
    blocks[:] = translated_blocks[block_states]
IndexError: index 28 is out of bounds for axis 0 with size 28
```

This is the config file that I am using as well.
```
worlds["main"] = "/opt/minecraft/fabric/world"

renders['world_day'] = {
    'world': 'main',
    'title': 'main',
    'rendermode': 'smooth_lighting',
}

outputdir = "/home/tbm/htmltest/"
texturepath = "/opt/minecraft/overviewer/textures/"
```

I'm not sure the best way to supply the portion of the world that seems to be causing the issue, I could do some world edit magic if needed.

Thanks!

**Comment by CounterPillow** [comment] 2020-07-01 22:11
please give me your r.0.1.mca. You should be able to drag-and-drop it into the little line at the bottom of the comment text box.

**Comment by ToastyBreadMan** [comment] 2020-07-01 23:25
Here it is.
[r.0.1.mca.zip](https://github.com/overviewer/Minecraft-Overviewer/files/4861251/r.0.1.mca.zip)

**Comment by ujifgc** [comment] 2020-07-02 07:13
Similar error here, new world generated in 0.16
Minecraft Overviewer version 0.15.75 (9605bd8)

```
2020-07-02 11:10:22 E Could not render chunk 10,-8 for some reason. This is likely a render primitive option error.
2020-07-02 11:10:22 E Full error was:
Traceback (most recent call last):
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1663, in get_chunk
    chunk_data = dict(super(RotatedRegionSet, self).get_chunk(x,z))
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1788, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1461, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1278, in _get_blockdata_v113
    blocks[:] = translated_blocks[block_states]
IndexError: index 24 is out of bounds for axis 0 with size 17
2020-07-02 11:10:24 E Could not render chunk 10,-8 for some reason. This is likely a render primitive option error.
2020-07-02 11:10:24 E Full error was:
Traceback (most recent call last):
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1663, in get_chunk
    chunk_data = dict(super(RotatedRegionSet, self).get_chunk(x,z))
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1788, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1461, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/home/ujif/Minecraft-Overviewer/overviewer_core/world.py", line 1278, in _get_blockdata_v113
    blocks[:] = translated_blocks[block_states]
IndexError: index 24 is out of bounds for axis 0 with size 17
```

**Comment by fhavio** [comment] 2020-07-02 11:29
Error persist on version 0.15.81. 

Have deleted the identified chunk on the mca file and error still persist on the same chunk. 
Also is it suppose for this version already support 1.16.1 features?
Also tried to change the texture pack to 1.16 but it insists that only support 1.15 textures.

I'm attaching the mca file, the chunk is 44,51
[backup_r.1.1.mca.zip](https://github.com/overviewer/Minecraft-Overviewer/files/4863838/backup_r.1.1.mca.zip)

This error is shown 5 times

> 2020-07-02 11:19:04 E Could not render chunk 44,51 for some reason. This is likely a render primitive option error.ta 07h 14m 43s
2020-07-02 11:19:04 E Full error was:
Traceback (most recent call last):
  File "/usr/lib/python3.5/dist-packages/overviewer_core/tileset.py", line 1093, in _render_rendertile
    self.options['rendermode'], self.textures)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1788, in get_chunk
    retval = super(CachedRegionSet, self).get_chunk(x,z)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1603, in get_chunk
    return self._r.get_chunk(x,z)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1461, in get_chunk
    (blocks, data) = self._get_blockdata_v113(section, unrecognized_block_types, longarray_unpacker)
  File "/usr/lib/python3.5/dist-packages/overviewer_core/world.py", line 1278, in _get_blockdata_v113
    blocks[:] = translated_blocks[block_states]
IndexError: index 14 is out of bounds for axis 0 with size 14

**Comment by Droon99-Developer** [comment] 2020-07-02 11:47
We used MCA Selector to purge chunks that were inhabited for less than 30 seconds, and that seemed to fix the problem from what we could see

**Comment by CounterPillow** [comment] 2020-07-02 11:56
> Error persist on version 0.15.81.

because I haven't had time to fix it yet, hence why the issue is still open.

>  Also is it suppose for this version already support 1.16.1 features?

It should render 1.16 worlds without crashing, and it not doing so is a bug that I will hopefully fix in the near future.

**Comment by CounterPillow** [comment] 2020-07-03 17:02
Not super sure what's going on here. The BlockStates array unpacks into something that requests palette entries above index 27 for a palette of size 28. However, they're not super far above, most of them are 28, and I see some 30 in there. @iRath96 do you know what's happening here?

**Comment by ujifgc** [comment] 2020-07-03 17:10
> We used MCA Selector to purge chunks that were inhabited for less than 30 seconds, and that seemed to fix the problem from what we could see

Tried to do what you suggest, but another chunk with the same problem appeared further down the render.

**Comment by Droon99-Developer** [comment] 2020-07-04 15:50
> > We used MCA Selector to purge chunks that were inhabited for less than 30 seconds, and that seemed to fix the problem from what we could see
> 
> Tried to do what you suggest, but another chunk with the same problem appeared further down the render.

We've sadly started getting this issue as well, with both the main and @iRath96's forks

**Comment by filips123** [comment] 2020-07-05 14:35
I have similar issue on world that was updated from 1.15.2 to 1.16.1. World rendered succesfully on 1.15.2 version, but after updating to 1.16.1, it fails. Render was compeltely new and does not contain any 1.15.2 cache.

I want to just render spawn, so I used `crop` option in config file:

```py
worlds["world"] = r"D:\Users\filips\Downloads\spawn\world"

renders["spawn-day"] = {
    "world": "world",
    "title": "Spawn Daytime",
    "rendermode": smooth_lighting,
     "crop": (-350, -230, 140, 260),
}

renders["spawn-night"] = {
    "world": "world",
    "title": "Spawn Nighttime",
    "rendermode": smooth_night,
    "crop": (-350, -230, 140, 260),
}

outputdir = r"D:\Users\filips\Downloads\spawn\render"
```

While running, I get a bunch of `IndexError`s. After some time, the program hangs and doesn't restore even after few minutes.

```
2020-07-05 16:28:55  Welcome to Minecraft Overviewer version 0.15.82 (d362e15)!
2020-07-05 16:28:55  Generating textures...
2020-07-05 16:29:06  Preprocessing...
2020-07-05 16:29:19  Rendered 0 of 1564.  0% complete.  ETA: ------
2020-07-05 16:29:39  Rendered 11 of 1564.  0% complete.  ETA: 00h 47m 13s
2020-07-05 16:29:39  Rendered 21 of 1564.  1% complete.  ETA: 00h 24m 40s
2020-07-05 16:29:39  Rendered 33 of 1564.  2% complete.  ETA: 00h 15m 39s
2020-07-05 16:29:39  Rendered 43 of 1564.  2% complete.  ETA: 00h 11m 59s
2020-07-05 16:29:39  Rendered 54 of 1564.  3% complete.  ETA: 00h 09m 33s
2020-07-05 16:29:39  Rendered 65 of 1564.  4% complete.  ETA: 00h 07m 54s
2020-07-05 16:29:40  Rendered 75 of 1564.  4% complete.  ETA: 00h 06m 50s
2020-07-05 16:29:40  Rendered 86 of 1564.  5% complete.  ETA: 00h 05m 58s
2020-07-05 16:29:40  Rendered 98 of 1564.  6% complete.  ETA: 00h 05m 13s
2020-07-05 16:29:40  Rendered 148 of 1564.  9% complete.  ETA: 00h 03m 24s
2020-07-05 16:29:41  Rendered 201 of 1564.  12% complete.  ETA: 00h 02m 26s
2020-07-05 16:29:41  Rendered 252 of 1564.  16% complete.  ETA: 00h 01m 54s
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
2020-07-05 16:29:42  Rendered 305 of 1564.  19% complete.  ETA: 00h 01m 34s
2020-07-05 16:29:42  Rendered 355 of 1564.  22% complete.  ETA: 00h 01m 20s
2020-07-05 16:29:43  Rendered 406 of 1564.  25% complete.  ETA: 00h 01m 09s
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
2020-07-05 16:29:44  Rendered 458 of 1564.  29% complete.  ETA: 00h 01m 00s
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
2020-07-05 16:29:47  Rendered 563 of 1564.  35% complete.  ETA: 00h 00m 49s
2020-07-05 16:29:49  Rendered 664 of 1564.  42% complete.  ETA: 00h 00m 41s
2020-07-05 16:29:51  Rendered 764 of 1564.  48% complete.  ETA: 00h 00m 33s
2020-07-05 16:29:55  Rendered 864 of 1564.  55% complete.  ETA: 00h 00m 29s
2020-07-05 16:30:00  Rendered 964 of 1564.  61% complete.  ETA: 00h 00m 25s
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
ERROR:root:Could not render chunk -13,0 for some reason. This is likely a render primitive option error.
ERROR:root:Full error was:
Traceback (most recent call last):
  File "overviewer_core\tileset.py", line 1093, in _render_rendertile
  File "overviewer_core\world.py", line 1717, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1788, in get_chunk
  File "overviewer_core\world.py", line 1603, in get_chunk
  File "overviewer_core\world.py", line 1461, in get_chunk
  File "overviewer_core\world.py", line 1278, in _get_blockdata_v113
IndexError: index 12 is out of bounds for axis 0 with size 9
```

I can then view the render, but a lot of chunks and images are missing, which basically makes render useless.

I guess I can't just delete chunks that cause errors, because then they would be missing from render and would again make render not complete.

**Comment by iRath96** [comment] 2020-07-06 17:55
> Not super sure what's going on here. The BlockStates array unpacks into something that requests palette entries above index 27 for a palette of size 28. However, they're not super far above, most of them are 28, and I see some 30 in there. @iRath96 do you know what's happening here?

They're not super far above because they are limited to 5 bits in this particular case (i.e. they cannot go above 31 anyway). I have manually calculated what the block states should unpack to for a few blocks and it turns out that `section['BlockStates']` itself contains invalid values. It's definitely not the region file itself that is corrupted, because Minecraft reads it just fine. Even though it's unlikely, this can only be due to one of these reasons I think:
* `section['BlockStates']` is corrupted somewhere in the code,
* there is a very rare bug in the NBT reader, or
* there is some special case for unpacking block states that has not been documented anywhere yet.

I hope this helps a bit. I'll try to investigate more when time permits.

**Comment by Droon99-Developer** [comment] 2020-07-08 22:41
Something to do with this change perhaps? @iRath96 @CounterPillow 

>   BlockStates in Sections elements no longer contain values stretching over multiple 64-bit fields.
        If the number of bits per block is not power of two (i.e. single 64-bit value can't fill whole number of blockstates) some bits will not be used.
        For example, if a single block state takes 5 bits, the highest 4 bits of every 64-bit field will be unused. That also means a slight increase in storage size (in case of 5 bits, from 320 to 342 64-bit fields).
[https://www.minecraft.net/en-us/article/nether-update-java](url)

**Comment by iRath96** [comment] 2020-07-09 06:36
@Droon99-Developer No, that has already been implemented in 5ff3e2b09f07092b88c073f04aaa15782395cf2a. I have also verified that the code is correct and behaves like documented by Mojang. The issue is that `section['BlockStates']` contains longs with invalid values, and I am not yet sure why.

**Comment by iRath96** [comment] 2020-07-09 14:55
I have verified with another NBT library that the file is read correctly. Turns out this really is an issue with the region file itself. It contains the block state `109806442814906498` in chunk 16/46, which asks for a palette index of `28`, which simply does not exist (since the palette only has 28 entries). In other words, there seems to be a mismatch between the information Mojang has given us about how block states are packed and the way they are really packed by Minecraft in a few rare special cases. At this point I am guessing it might make sense to report this as a bug on Mojang's bug tracker.

**Comment by CounterPillow** [comment] 2020-07-09 15:34
To reverse engineer what Minecraft does, it could be helpful if somebody could create a minimal chunk (i.e. not something Minecraft generated) that exhibits this problem so we can easily see how all the blocks are shown in Minecraft; that way we can work backwards from that. Very annoying problem though, and yeah, probably a bug in Minecraft.

**Comment by CounterPillow** [comment] 2020-07-09 16:03
I've played around with a void Minecraft world, placed exactly 27 different blocks in a chunk (+1 with air), verified that I've gotten a palette of size 28 in that section but curiously no crash; however, my blockstates long array is only 342 long integers as opposed to 410 longs in one submitted sample.

@fhavio I cannot actually use your sample because the chunk you're struggling with has been deleted from it. I believe you have accidentally deleted the chunk in your backup version and kept it in your actual region file, which would explain why you still have issues after deleting said chunk.

**Comment by CounterPillow** [comment] 2020-07-09 16:14
Since 16 \* 16 \* 16 = 4096 < (64 // 5) \* 342, I've decided that the correct course of action in attempting to recreate such a chunk is to place more than 2^5 different blocks, and then remove them. I did this, verifying that Minecraft expanded my blockstates to 410 long ints. Cool! Then I removed them. Minecraft shrunk it back to 342 long ints. Huh.

**Comment by CounterPillow** [comment] 2020-07-09 16:37
I've added a workaround that should ensure that Overviewer will no longer crash on this issue. Please let me know if it still manages to crash somehow.

**Comment by iRath96** [comment] 2020-07-09 16:47
@CounterPillow I've tried a workaround like this while debugging as well. Sadly, renders of the affected chunks will look completely scrambled. I struggle to understand how Minecraft is able to correctly read such chunks 🤷

**Comment by fhavio** [comment] 2020-07-09 16:57
Hey @CounterPillow  for some reason the file i attached here cant be open on NBT (strange!) but ok
i check my region file and it was with the chunk deleted, the one i shared here was suppose to have the chunk so you guys could see whats up with it.

I'm running now a render lets see if it fix this issue. Thank you for all the work. As soon i have feedback will let you know.
BR,

**Comment by Droon99-Developer** [comment] 2020-07-09 17:48
My render appears to have completed correctly! No errors noticed

**Comment by CounterPillow** [comment] 2020-07-09 20:23
@iRath96 for the only applicable sample file provided, the output seems to produce correct results as far as I can see.

@fhavio
>  The one i shared here was suppose to have the defect chunk, so you guys could see whats up with it.

It doesn't.
![image](https://user-images.githubusercontent.com/308818/87087063-bcce2000-c232-11ea-813b-5bcc97de9b77.png)

**Comment by fhavio** [comment] 2020-07-09 20:34
Seems i have mistaked the files.
But its already at 8%, before it stucked at 1% so it probably will render.
Lets see in the morning, its a server map and since i'm making a clean render of it will take time.

**Comment by Droon99-Developer** [comment] 2020-07-10 21:44
I locally merged @iRath96's block-model branch with your fix and all seems to work well, no issues noticed

**Comment by drwhitehouse** [comment] 2020-07-12 08:37
I updated my world to 1.16.1 yesterday and after rebuilding with: python3 setup.py build I can render my world with no errors, however newer poi do not appear to be found.

**Comment by Droon99-Developer** [comment] 2020-07-15 13:58
Looks like the bad chunks are still there
![Screenshot_20200715_095804](https://user-images.githubusercontent.com/5342765/87554164-c9fb6c80-c681-11ea-9d53-82761918ea99.png)

**Comment by CounterPillow** [comment] 2020-07-15 14:01
Please submit a sample, a screenshot isn't of much use.

**Comment by Droon99-Developer** [comment] 2020-07-15 14:27
Heres a few regions that had bad chunks. I observed that the odd behavior only seemed to go a few blocks down (see the included screenshot) I'm going to attempt to build something in one of these chunks and see what happens
![Screenshot_20200715_102722](https://user-images.githubusercontent.com/5342765/87557358-d08be300-c685-11ea-8850-f556a71ab714.png)

[Weird Regions.zip](https://github.com/overviewer/Minecraft-Overviewer/files/4925838/Weird.Regions.zip)

**Comment by Auron956** [comment] 2020-07-15 22:50
Testing on my end suggests the calculation for `bits_per_value` within function `_packed_longarray_to_shorts_v116` doesn't always produce the correct result, which as far as I can tell is the cause of these issues. Amending the calculation as below seemed to fix this for me (at least for the region files provided above):
`bits_per_value = max(4, (len(long_array) * 64) // n)`

This may also mean the workaround implemented in 8c0028495dd3ef745efdae9b06020f8686ab4fdc is no longer required, although I haven't done enough testing to be sure of this.

**Comment by Gaz492** [comment] 2020-07-16 00:48
> Testing on my end suggests the calculation for `bits_per_value` within function `_packed_longarray_to_shorts_v116` doesn't always produce the correct result, which as far as I can tell is the cause of these issues. Amending the calculation as below seemed to fix this for me (at least for the region files provided above):
> `bits_per_value = max(4, (len(long_array) * 64) // n)`
> 
> This may also mean the workaround implemented in [8c00284](https://github.com/overviewer/Minecraft-Overviewer/commit/8c0028495dd3ef745efdae9b06020f8686ab4fdc) is no longer required, although I haven't done enough testing to be sure of this.

Looks like changing the bits_per_value like you said allowed me to render my world without issues

**Comment by iRath96** [comment] 2020-07-16 06:40
@Auron956 as per Mojang's documentation, `bits_per_value` should really not depend on the size of the `long_array`. I guess this means their documentation is probably incomplete 🤷 . What worries me, however, is that your code assumes that a chunk with a palette size in the range 1024–2047 requires 12 bits to store each block state, even though (according to Mojang) only 11 bits would really be used. (Then again, having a chunk with 1024 different blocks is quite unlikely, so this can probably be neglected)

**Comment by Auron956** [comment] 2020-07-16 12:45
@iRath96 what Mojang documentation is it that you're referring to? I'm aware that the change to block storage is mentioned within the [20W17A snapshot news article](https://www.minecraft.net/en-us/article/minecraft-snapshot-20w17a), although I can't see any suggestion there as to how the number of bits per block should be determined for a given chunk.

But yes, admittedly my suggestion is merely based on observations from some of the provided region files rather than any sort of specification or documentation from Mojang (or elsewhere). In addition testing has not been extensive, (and certainly did not cover the case you've rightfully pointed out) so I can't be certain it would function properly in all cases.

**Comment by iRath96** [comment] 2020-07-16 17:28
@Auron956 yes, I was referring to the 20W17A article. You're right, they're not explicitly stating how many bits there should be per block state. Some site stated that the bits used would be the least amount required to map each block in the palette (which would make perfect sense), but that was probably some unofficial site.

**Closed** 2020-07-28 11:09 UTC
Labels: Bug, Under Investigation

**Comment by CounterPillow** [comment] 2020-07-28 11:10
Thanks for looking into it, I've verified and applied the fix. In the future I'll make sure to ask for the block parsing routine's origin during reviews so I can verify that the specification as laid out by Mojang has been implemented correctly.
