### ISSUE TITLE
Windows error 183

### ISSUE THREAD

**Issue by rwisckol** [overviewer/Minecraft-Overviewer#1360] opened 2017-01-24 15:01 UTC
I recently downloaded v0.12.137 and encountered an issue when trying to use the --genpoi tag.  Rendering the map the first time (outputdir empty) seems to work fine.  If I re-run it after adding additional POI's to the PY file, I receive the error at the end of the process and any new POI's are not included in the output.  I'm running it on an older system with Windows 10 installed.

Attached please find a copy of the PY file as well as a screenshot of the error.  

Thanks for your attention to this and I'd appreciate any corrective suggestions you may have if any are to be had on this end.  Overview is a fantastic application and I've used it for years to support my SSP worlds as well as some small-medium realms worlds and hope a solution is available :)

[MesaVerde.py.txt](https://github.com/overviewer/Minecraft-Overviewer/files/727016/MesaVerde.py.txt)
![overviewerror](https://cloud.githubusercontent.com/assets/25325020/22252407/13b91ef6-e21c-11e6-9f2d-54ea6c63a5cf.jpg)

**Comment by CounterPillow** [comment] 2017-01-26 10:03
Duplicate of #1271

**Closed by CounterPillow** 2017-01-26 10:03 UTC
