### ISSUE TITLE
I can't install minecraft overviewer on CentOS 7!

### ISSUE THREAD

**Issue by Luukth** [overviewer/Minecraft-Overviewer#1214] opened 2015-03-03 13:33 UTC
When I try to install minecraft overviewer on my vps I get this error:

[root@play yum.repos.d]# yum install Minecraft-Overviewer
Loaded plugins: fastestmirror
base                                                     | 3.6 kB     00:00
epel/x86_64/metalink                                     |  14 kB     00:00
extras                                                   | 3.4 kB     00:00
http://overviewer.org/rpms/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found
Trying other mirror.

 One of the configured repositories failed (Minecraft-Overviewer - 7 - x86_64),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Disable the repository, so yum won't use it by default. Yum will then
        just ignore the repository until you permanently enable it again or use
        --enablerepo for temporary usage:

            yum-config-manager --disable overviewer

     4. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=overviewer.skip_if_unavailable=true

failure: repodata/repomd.xml from overviewer: [Errno 256] No more mirrors to try.
http://overviewer.org/rpms/7/x86_64/repodata/repomd.xml: [Errno 14] HTTP Error 404 - Not Found

**Comment by tswsl1989** [comment] 2015-03-03 13:42
This is a duplicate of #1204. Take a look at that issue for current progress and a couple of workarounds.

**Closed by tswsl1989** 2015-03-03 13:42 UTC
