### ISSUE TITLE
Segfault while generating textures

### ISSUE THREAD

**Issue by stwalkerster** [overviewer/Minecraft-Overviewer#1575] opened 2019-05-09 07:35 UTC
Attempting to render a 1.14 world causes a segmentation fault almost immediately.

```
bash $ /usr/bin/overviewer.py --config=tmpconfig
2019-05-09 08:30:25  Welcome to Minecraft Overviewer!
2019-05-09 08:30:25  Generating textures...
Segmentation fault (core dumped)

bash $ /usr/bin/overviewer.py --version
Minecraft Overviewer 0.13.88 (c45ffcb)
built on Sun May  5 13:21:01 2019

bash $ apt-cache policy minecraft-overviewer
minecraft-overviewer:
  Installed: 0.13.88-0~overviewer1
  Candidate: 0.13.88-0~overviewer1
  Version table:
 *** 0.13.88-0~overviewer1 500
        500 https://overviewer.org/debian ./ Packages
        100 /var/lib/dpkg/status
...
```

Config:
```
outputdir = "maps-pillage"

worlds["pillage"] = "worlds/pillage/world"

renders["pillage-overworld-day-north"] = {
	"title": "render",
        "world": "pillage",
        "dimension": "overworld",
        "northdirection": "upper-left",
}
```
Stack trace:
```
Starting program: /usr/bin/python /usr/bin/overviewer.py --config=tmpconfig
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
2019-05-09 08:32:02  Welcome to Minecraft Overviewer!
2019-05-09 08:32:02  Generating textures...

Program received signal SIGSEGV, Segmentation fault.
0x00007ffff65402fd in alpha_over_wrap () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
(gdb) bt
#0  0x00007ffff65402fd in alpha_over_wrap () from /usr/lib/python2.7/dist-packages/overviewer_core/c_overviewer.so
#1  0x000055555564a4ca in PyEval_EvalFrameEx ()
#2  0x000055555564f232 in PyEval_EvalFrameEx ()
#3  0x000055555564f232 in PyEval_EvalFrameEx ()
#4  0x0000555555647d0a in PyEval_EvalCodeEx ()
#5  0x000055555564fc38 in PyEval_EvalFrameEx ()
#6  0x0000555555647d0a in PyEval_EvalCodeEx ()
#7  0x0000555555647629 in PyEval_EvalCode ()
#8  0x000055555567861f in ?? ()
#9  0x0000555555673322 in PyRun_FileExFlags ()
#10 0x000055555567267d in PyRun_SimpleFileExFlags ()
#11 0x00005555556211ab in Py_Main ()
#12 0x00007ffff7a05b97 in __libc_start_main (main=0x555555620b10 <main>, argc=3, argv=0x7fffffffe418, init=<optimised out>, fini=<optimised out>, rtld_fini=<optimised out>, stack_end=0x7fffffffe408)
    at ../csu/libc-start.c:310
#13 0x0000555555620a2a in _start ()
```

**Comment by CounterPillow** [comment] 2019-05-09 10:32
Duplicate of #1423

**Closed by CounterPillow** 2019-05-09 10:32 UTC
