### ISSUE TITLE
Overviewer for Windows x64 0.12.204 Release Date??

### ISSUE THREAD

**Issue by fhavio** [overviewer/Minecraft-Overviewer#1412] opened 2017-09-15 10:53 UTC
Hello,

I saw that you have in the repository the new version for Windows.
http://static.overviewer.org/builds/master/861/

I render the 1st time in png and it is ok but i really want to decrease the size of the render, so i test for jpeg/jpg and its giving me an error in the conversion library.
Could you tell when you expect to release the final version for Windows?

Best Regards

**Comment by CounterPillow** [comment] 2017-09-15 11:31
>and its giving me an error in the conversion library.

can you show us the error?

**Comment by fhavio** [comment] 2017-09-15 14:09
![image](https://user-images.githubusercontent.com/26770387/30486144-83c7e808-9a27-11e7-8d49-210115d76f40.png)

Also is there other ways to make the render occupying less space?
If i render with png even with quality set to 10, i have 20gb of render this is a lot.

	'imgformat':'png',
	'imgquality':'10',

**Comment by CounterPillow** [comment] 2017-09-15 14:31
Strange, will need further investigation. I don't know whether the builds there use PIL or Pillow, so I'm not sure what the problem is.

As for the imgquality thing, it doesn't apply to PNG. PNG is a lossless format. If you want to apply lossy quantisation on top of PNG, try the `pngnq` optimiser for `optimizeimg`.

**Comment by fhavio** [comment] 2017-09-15 16:20
CAn you help me with the optimizer, it's giving me this error

![image](https://user-images.githubusercontent.com/26770387/30492860-e10cc0d0-9a39-11e7-976f-3f9c6cbf41e8.png)

I understand that the programs are missing, i download the pngnq-s9 and pngnq, but this second one dont have any execute file (.exe)
Also can you give me an example of how i need to setup them in the environmental variables?

**Comment by CounterPillow** [comment] 2017-09-15 16:36
Try putting it in the same directory as overviewer.exe

**Comment by fhavio** [comment] 2017-09-15 16:41
I had already place it there but same error

![image](https://user-images.githubusercontent.com/26770387/30493646-dac8d012-9a3c-11e7-840c-2ac9ca216c94.png)

Do i have to compile in some way the pngnq.exe file? because i dont have it..

**Comment by CounterPillow** [comment] 2017-09-15 16:42
no, overviewer will either use pngnq-s9.exe or pngnq.exe, whichever is found.

Put it in a new directory, and then append that directory to your `%PATH%` environment variable.

**Comment by Reg-Ed** [comment] 2017-09-16 10:00
I don't want to seem ungrateful becuase I know you guys do this all completely for free and in your own time, and I truly appreciate the resource, but I too am desperately waiting for a Windows release of 0.12.204 (or whatever is the newest version at the time).

I'm not sure why the Windows version has fallen so far behind this time, it's usually released in line with the other major Linux releases.

In other threads people have even offered to help out by compiling the Windows builds for you, but received no reply.  Is the project winding down?

**Comment by CounterPillow** [comment] 2017-09-22 09:32
@Reg-Ed 
>I'm not sure why the Windows version has fallen so far behind this time, it's usually released in line with the other major Linux releases.

because our automatic Windows builders are down. At some point, the VMs we were using previously (which were provided by someone who's not around anymore) disappeared.

>In other threads people have even offered to help out by compiling the Windows builds for you, but received no reply.

We can manually compile Windows builds ourselves, this is not the problem. The problem is that the automatic build infrastructure fell victim to bitrot, and the replacement was never properly finished. It's a problem with the infrastructure; some VMs need to be moved around and the new infra needs to be plugged into the overviewer website. So basically, there's not much anyone from the outside can do other than run their own automatic build infrastructure.

>Is the project winding down?

none of the core devs have played much Minecraft in the last few years.

I appreciate your concern and apologise for the current circumstances.

**Comment by eminence** [comment] 2018-01-06 18:28
The https://overviewer.org/downloads page now lists the latest windows builds, so I'm going to close this issue.

**Closed by eminence** 2018-01-06 18:28 UTC
