### ISSUE TITLE
Uable to view map as a web URL

### ISSUE THREAD

**Issue by Krahazik** [overviewer/Minecraft-Overviewer#1317] opened 2016-08-01 21:54 UTC
I am unable to view the output "index.html" file as a web address. Examples below:

WORKS = file:///C:/inetpub/minecraft/map/index.html

ERROR = http://minecraft.ruby-dragon.net/map/index.html

> Oops! Something went wrong. 
This page didn't load Google Maps correctly. See the JavaScript console for technical details.

Tried both on the same computer, (the one running minecraft and the IIS web server.) in the same browser window side by side as 2 different tabs. Opening as a local file it displayed the map, opening as a web address via the web server produced the error page.

Console output that my browser provided for the error as follows:

```html
GET http://minecraft.ruby-dragon.net/map/progress.json?_=1470088054667
	
404 Not Found
		36ms	
jquery.min.js (line 5)
ParamsHeadersResponseHTMLCookies

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict
.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
<title>404 - File or directory not found.</title>
<style type="text/css">
<!--
body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}

fieldset{padding:0 15px 10px 15px;} 
h1{font-size:2.4em;margin:0;color:#FFF;}
h2{font-size:1.7em;margin:0;color:#CC0000;} 
h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;} 
#header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif
;color:#FFF;
background-color:#555555;}
#content{margin:0 0 0 2%;position:relative;}
.content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
-->
</style>
</head>
<body>
<div id="header"><h1>Server Error</h1></div>
<div id="content">
 <div class="content-container"><fieldset>
  <h2>404 - File or directory not found.</h2>
  <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily
 unavailable.</h3>
 </fieldset></div>
</div>
</body>
</html>

"NetworkError: 404 Not Found - http://minecraft.ruby-dragon.net/map/progress.json?_=1470088054667"
progres...8054667
Google Maps API error: MissingKeyMapError https://developers.google.com/maps/documentation/javascript/error-messages#missing-key-map-error
	

...nction(){a.apply(b,c)})}};_.Wa=function(a){return window.setTimeout(a,0)};Ya=fun...

js?sensor=false (line 31)
2
TypeError: d is undefined
	

...a.ka.remove(d)})},l_=function(a,b,c,d){b=d.fromLatLngToPoint(b);d=d.fromLatLngTo...

	
marker.js (line 28, col 72)
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys
util.js (line 210)
Google Maps API warning: SensorNotRequired https://developers.google.com/maps/documentation/javascript/error-messages#sensor-not-required
util.js (line 210)
```

**Comment by CounterPillow** [comment] 2016-08-01 23:42
Duplicate of #1308.

**Comment by rbelknap** [comment] 2016-08-01 23:42
Krahazik, Google maps requires an API key now to use:

https://github.com/overviewer/Minecraft-Overviewer/issues/1308#issuecomment-228310624

**Closed by CounterPillow** 2016-08-01 23:42 UTC
