### ISSUE TITLE
1.15 jar not working for texture generation

### ISSUE THREAD

**Issue by ichttt** [overviewer/Minecraft-Overviewer#1687] opened 2019-12-11 22:19 UTC
With only the 1.15 jar present, overviewer fails with the following error:

`2019-12-11 23:16:21 E Could not find the textures while searching for 'assets/minecraft/textures/entity/chest/normal_double.png'. Try specifying the 'texturepath' option in your config file.
Set it to the path to a Minecraft Resource pack.
Alternately, install the Minecraft client (which includes textures)
Also see <http://docs.overviewer.org/en/latest/running/#installing-the-textures>
(Remember, this version of Overviewer requires a 1.14-compatible resource pack)
(Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)`

If the 1.14.4 jar exists as well, the texture get generated without problems

**Comment by CounterPillow** [comment] 2019-12-11 22:57
We best start requiring a 1.15 jar once we add actual 1.15 textures I guess.

**Comment by ncarroll0488** [comment] 2019-12-13 18:12
As a really dirty trick, you can just copy in the missing 1.14 asset files into the 1.15 dir
`rsync -a --ignore-existing /path/to/1.14/ /path/to/1.15/` (trailing slash very important)
This works provided you have no new 1.15 blocks on the map. I have no idea what happens otherwise.

**Comment by Gyzie** [comment] 2019-12-26 19:46
The issue is that Mojang changed chest textures and their name (and maybe even more textures). What fix do we desire?:
- Updating the texture code so chest are only rendered correctly on 1.15 textures.
- Trying to support 1.14 and 1.15 textures by creating more complexity in the chest code.

**Comment by Gyzie** [comment] 2019-12-26 23:18
Fixed in PR #1702

**Closed** 2019-12-27 13:49 UTC
Labels: Minecraft 1.15
