### ISSUE TITLE
Generating blank tiles when rendering 21w37a/21w38a snapshot

### ISSUE THREAD

**Issue by pietrobenito** [overviewer/Minecraft-Overviewer#1982] opened 2021-09-24 18:57 UTC
Has anyone else tried running Overviewer on a world from one of the latest snapshots?

My render seems to be executing but all the rendered tiles are blank (all the same filesize).

**Comment by C-Dever** [comment] 2021-10-03 17:15
I have this issue too. I also noticed that any chunks loaded in 1.18 snapshots (even 1.17 and earlier terrain) show up as blank tiles now. Not sure what the issue is and the chunks in the actual world seem to be saved perfectly fine, it's just the renderer is unable to actually render the tiles.

**Comment by jmspoonerhfr** [comment] 2021-10-11 14:19
same here overviewer 0.17.0 snapshot 21w40a... also using the snapshot client jar for textures

**Comment by rjp** [comment] 2021-10-30 15:21
Doesn't seem to be an Overviewer-specific issue, FWIW; both the `fast-nbt` tile rendering and `mcmap` are generating entirely blank output for me on a 21w42a world.

**Comment by Homeboy87** [comment] 2021-11-03 19:01
after Upgrading the World from snapshot  21w43a to snapshot 21w44a, i get this error for the world while rendering 

```
2021-11-03 19:38:51  Welcome to Minecraft Overviewer version 0.17.39 (2402e41)!
2021-11-03 19:38:51  Generating textures...
2021-11-03 19:39:06 E An error has occurred. This may be a bug. Please let us know!
See http://docs.overviewer.org/en/latest/index.html#help

This is the error that occurred:
Traceback (most recent call last):
  File "/usr/bin/overviewer.py", line 653, in <module>
    ret = main()
  File "/usr/bin/overviewer.py", line 562, in main
    tileSetOpts.update({"spawn": w.find_true_spawn()})  # TODO find a better way to do this
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 221, in find_true_spawn
    chunk = regionset.get_chunk(chunkX, chunkZ)
  File "/usr/lib/python3/dist-packages/overviewer_core/world.py", line 1637, in get_chunk
    level = data[1]['Level']
KeyError: 'Level'
```

also happend with a new generatet world

**Comment by 26** [comment] 2021-11-07 22:55
The pull request listed above aims to fix these issues.

**Comment by ClaffyBob** [comment] 2021-11-22 23:11
> The pull request listed above aims to fix these issues.

@26, I am having the same issue as @Homeboy87 ... How do we get this merged and released?

**Comment by 26** [comment] 2021-11-23 06:07
> > The pull request listed above aims to fix these issues.
> 
> @26, I am having the same issue as @Homeboy87 ... How do we get this merged and released?

We will have to wait until one of the developers merges it. You can try to use my fork in the meantime and compile from source.

**Comment by IncredibleHolg** [comment] 2021-12-01 11:35
If you want to use the pull request code

```bash
git fetch origin pull/1990/head:u118
git checkout  u118
python3 setup.py build
```

**Comment by ClaffyBob** [comment] 2021-12-01 13:15
I used @26 fork in a dockerfile project (that I forked) and pushed that to dockerhub. It's working for me now...

**Closed** 2021-12-02 17:58 UTC
Labels: Needs Investigation, Bug, World Reading, Minecraft 1.18
