### ISSUE TITLE
Chunks and tiles being rendered in wrong place on partial updates.  Full render works fine.

### ISSUE THREAD

**Issue by dankingdon** [overviewer/Minecraft-Overviewer#1384] opened 2017-06-08 19:56 UTC
Hi,

I am playing with the overviewer system and everything is working great, except when re-rendering our world.  Certain chunks appear in the wrong place and some of the zoom level tiles are not being updated creating a weird border issues.  The map is fine and we are running vannilla 1.11 with no  mods or customisation.

Deleting the world and re-rendering or using force render works fine.

Any suggestions?  A full render takes 3-4 hours so I would rather not schedule that regularly.

See picture for example, note the chunk split in half near the lava on the left side.  The chunk of coast/sugar canes in the middle of the wheat farm, and the large stone walls from mountain chunks in the wrong place.
![image](https://user-images.githubusercontent.com/23501040/26948026-d9130952-4c8c-11e7-973d-7a85f68318f3.png)

**Comment by diabolicallyrandom** [comment] 2017-06-11 06:26
I am wondering if the issue I am having is related. If I do a full fresh render it works fine, but if i do a normal update render, I end up with this issue:

![capture](https://user-images.githubusercontent.com/1214344/27008892-3decc7c0-4e34-11e7-9412-f88931824539.PNG)

**Comment by CounterPillow** [comment] 2017-06-11 09:16
@diabolicallyrandom no, the original report is an old bug and has an issue open already but I can't be arsed to find it right now. Yours looks more like straight up image corruption of the tiles, judging by the random-looking pixels that appear.

**Comment by CounterPillow** [comment] 2017-06-11 09:18
closed as duplicate of #1178

**Closed by CounterPillow** 2017-06-11 09:18 UTC

**Comment by diabolicallyrandom** [comment] 2017-06-12 00:44
Thanks - I checked all the PNG files and they are good - tested in Edge with same results, but then I opened  a copy locally on my windows PC and it worked fine. So that suggests that somehow my apache server is causing corruption in the PNG files being sent over http:// - so technically unrelated to overviewer.

**Comment by diabolicallyrandom** [comment] 2017-06-12 01:04
Found my solution here and adapted to DEBIAN: https://www.cyberciti.biz/tips/tag/enablemmap

Apparently, apache has a couple of config options that cause it to choke when using network attached storage for the web document root:

EnableMMAP off
EnableSendfile off

I disabled those and everything works.

Posting here for anyone who finds this thread from google.
