### ISSUE TITLE
RConObserver error

### ISSUE THREAD

**Issue by marceltoepler** [overviewer/Minecraft-Overviewer#1273] opened 2016-01-29 22:35 UTC
I try to use RConObserver like this:
```
from observer import RConObserver
observer = RConObserver("127.0.0.1", "xxxxx", 25565)
```

When I try to run the overviewer now, following error appears:
```
2016-01-29 23:31:45 E Partial traceback:
  File "/usr/local/bin/minecraft-scripts/overviewer/config", line 21, in <module>
    observer = RConObserver("127.0.0.1", "xxxxx", 25565)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/observer.py", line 407, in __init__
    self.conn.login(password)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/rcon.py", line 89, in login
    self.send(3, password)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/rcon.py", line 71, in send
    res_len, res_id, res_type = struct.unpack("<iii", self.sock.recv(12))
error: unpack requires a string argument of length 12
```

Is my config wrong or someting else?

**Comment by CounterPillow** [comment] 2016-01-30 12:36
What version of the minecraft server are you trying to communicate with?

**Comment by CounterPillow** [comment] 2016-01-30 13:02
I just pushed a commit which may fix this, let me know if the error is gone now (and whether it was 100% reproducible in the first place)

**Comment by marceltoepler** [comment] 2016-01-30 13:33
I'm using Spigot version 1.8.
Using the patched version of rcon.py seems like the same error appears. :/

`
2016-01-30 14:27:59 E Partial traceback:
  File "/usr/local/bin/minecraft-scripts/overviewer/config", line 21, in <module>
    observer = RConObserver("127.0.0.1", "xxxxx", 25565)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/observer.py", line 407, in __init__
    self.conn.login(password)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/rcon.py", line 90, in login
    self.send(3, password)
  File "/usr/lib/python2.7/dist-packages/overviewer_core/rcon.py", line 72, in send
    struct.unpack("<iii", self.sock.recv(12, socket.MSG_WAITALL))
error: unpack requires a string argument of length 12
`

**Comment by CounterPillow** [comment] 2016-01-30 13:43
Huh, interesting. The only way this could happen as far as I can tell is if the rcon server closes the connection prematurely or if, according to the `recv(2)` man-page, a signal is caught or an error occurs.

Perhaps the password is invalid and spigot closes the connection immediately in that case? I'm just guessing though.

**Comment by marceltoepler** [comment] 2016-01-30 13:47
I'm using mcrcon too with the same credentials and it's working, so I think we can rule that out.

**Comment by CounterPillow** [comment] 2016-01-30 13:50
I'll try to reproduce this locally with spigot then so that I can investigate further, thanks for the quick responses.

**Comment by marceltoepler** [comment] 2016-01-30 13:58
Thank you!

**Comment by CounterPillow** [comment] 2016-01-30 14:03
I've tried reproducing locally with spigot, but with no success. Everything works fine here.

Can you upload the spigot jar you're using to https://overviewer.org/uploader/? That way I can test with the exact version you have.

Also, what OS/Distro are you on?

**Comment by CounterPillow** [comment] 2016-01-30 14:17
Okay, the issue here is the following: The thing you're talking to is not talking rcon.

What you used in "port" is not the rcon port, but the minecraft server port. Leaving out the port field (or correctly filling it out with the default 25575) will actually make it talk to the correct thing.

**Comment by marceltoepler** [comment] 2016-01-30 14:28
I see what you mean...
Sorry for the rubbish now it's working fine. :)

**Comment by CounterPillow** [comment] 2016-01-30 14:30
I added a more helpful error message in this case. I'll close this for now since it seems to work for you. Thanks for the issue anyway, this way people who run into this in the future will be more likely to find the solution.

**Closed by CounterPillow** 2016-01-30 14:30 UTC
