### ISSUE TITLE
How to modify texturepath?  I keep getting this error and I don't know what to do.

### ISSUE THREAD

**Issue by Azedus** [overviewer/Minecraft-Overviewer#1402] opened 2017-08-01 19:37 UTC
C:\Users\tyler\overviewer>overviewer.exe "%appdata%.minecraft\saves\Survival World S4" c:\users\tyler\desktop\mymap 2017-08-01 15:35:38 Welcome to Minecraft Overviewer! 2017-08-01 15:35:38 Generating textures... 2017-08-01 15:35:40 E Could not find the textures while searching for 'assets/minecraft/textures/blocks/bed_feet_top.png'. Try specifying the 'texturepath' option in your config file. Set it to the path to a Minecraft Resource pack. Alternately, install the Minecraft client (which includes textures) Also see http://docs.overviewer.org/en/latest/running/#installing-the-textures (Remember, this version of Overviewer requires a 1.10-compatible resource pack) (Also note that I won't automatically use snapshots; you'll have to use the texturepath option to use a snapshot jar)

**Comment by CounterPillow** [comment] 2017-08-01 19:57
Your problem is that your overviewer version isn't new enough to work with Minecraft 1.12, this is because we haven't put any updated Windows builds onto our download page. Duplicate of #1390

**Closed by CounterPillow** 2017-08-01 19:57 UTC
